export default {
        //App commun texts
        welcome: "THE EASIER WAY\nTO USE\nTHE ASTROPEDIA",
        userIdentification: "What is your\nAstroneer name?",
        language: "Language: ",
        whatYouWant: "Don't see what you want?",
        contactUs: "Contact Us",
        contactUsDefaultName: "Astroneer Player",
        contactUsMail: "noreply",
        contactUsMessageFrom: "\n\n\nMessage from: ",
        contactUsMessageReply: "\nReply to: ",
        contactUsWarning: "You need to include a message!",
        contactUsPlaceholderEmail: "Email",
        contactUsPlaceholderName: "Name",
        contactUsPlaceholderMessage: "Message",
        avatar: "Avatar: ",
        name: "Name: ",
        aboutUs: "About Us",
        aboutUsCredit: "Credits",
        aboutUsDeveloped: "Developed by MIDDLEWARE DEV",
        aboutUsDesign: "Design",
        aboutUsThanks: "With Special Thanks to",
        aboutUsTranslation: "Translations",
        warningTitle: "Warning",
        warningMessage: "The changes will only take effect after you restart the Astropedia",
        warningButton: "Ok",

        //Titles
        mainTitle: "Astropedia",
        planetsTitle: "Planets",
        resourcesTitle: "Resources",
        favoritesTitle: "Favorites",
        naturalResourcesTitle: "Natural Resources",
        atmosphericResourcesTitle: "Atmospheric Resources",
        sourceTitle: "Source",
        usesTitle: "Uses",
        printers: "Printers",
        settings: "Settings",

        //Planet's names
        sylva: "Sylva",
        desolo: "Desolo",
        calidor: "Calidor",
        vesania: "Vesania",
        novus: "Novus",
        glacio: "Glacio",
        atrox: "Atrox",

        //Basic Resource's names
        ammonium: "Ammonium",
        astronium: "Astronium",
        clay: "Clay",
        compound: "Compound",
        graphite: "Graphite",
        hematite: "Hematite",
        laterite: "Laterite",
        lithium: "Lithium",
        malachite: "Malachite",
        organic: "Organic",
        quartz: "Quartz",
        resin: "Resin",
        sphalerite: "Sphalerite",
        titanite: "Titanite",
        wolframite: "Wolframite",
        aluminum: "Aluminum",
        carbon: "Carbon",
        ceramic: "Ceramic",
        copper: "Copper",
        glass: "Glass",
        iron: "Iron",
        titanium: "Titanium",
        tungsten: "Tungsten",
        zinc: "Zinc",

        //Gas names
        argon: "Argon",
        helium: "Helium",
        hydrogen: "Hydrogen",
        methane: "Methane",
        nitrogen: "Nitrogen",
        sulfur: "Sulfur",

        //Compost Resourse name
        aluminumAlloy: "Aluminum Alloy",
        diamond: "Diamond",
        explosivePowder: "Explosive Powder",
        hydrazine: "Hydrazine",
        graphene: "Graphene",
        nanocarbonAlloy: "Nanocarbon Alloy",
        plastic: "Plastic",
        rubber: "Rubber",
        silicone: "Silicone",
        steel: "Steel",
        titaniumAlloy: "Titanium Alloy",
        tungstenCarbide: "Tungsten Carbide",

        //Sources and Items name
        sourceAllPlanets: "All Planets",
        solidFuelThruster: "Solid-Fuel Thruster",
        exoChip: "Exo Chip",
        packager: "Packager",
        solidFuelJumpJet: "Solid-Fuel Jump Jet",
        dynamite: "Dynamite",
        smallGenerator: "Small Generator",
        tether: "Tether",
        roverSeat: "Rover Seat",
        trailer: "Trailer",
        researchChamber: "Research Chamber",
        largeRoverSeat: "Large Rover Seat",
        buggy: "Buggy",
        splitter: "Splitter",
        autoArm: "Auto Arm",
        mediumBattery: "Medium Battery",
        rtg: "RTG",
        glowsticks: "Glowsticks",
        beacon: "Beacon",

        storageSensor: "Storage Sensor",
        mediumSensorArch: "Medium Sensor Arch",
        largeSensorRing: "Large Sensor Ring",
        largeSensorHoopA: "Large Sensor Hoop A",
        largeSensorHoopB: "Large Sensor Hoop B",
        xlSensorArch: "XL Sensor Arch",
        xlSensorCanopy: "XL Sensor Canopy",
        xlSensorHoopA: "XL Sensor Hoop A",
        xlSensorHoopB: "XL Sensor Hoop B",
        canister: "Canister",
        oxygenFilter: "Oxygen Filter",
        mediumStorage: "Medium Storage",
        mediumPlatformA: "Medium Platform A",
        mediumPlatformB: "Medium Platform B",
        mediumPlatformC: "Medium Platform C",
        largePlatformA: "Large Platform A",
        largePlatformB: "Large Platform B",
        oxygenator: "Oxygenator",
        mediumGenerator: "Medium Generator",
        mediumWindTurbine: "Medium Wind Turbine",
        tractor: "Tractor",

        largeTPlatform: "Large T-Platform",
        smallShuttle: "Small Shuttle",
        landingPad: "Landing Pad",
        drillMod1: "Drill Mod 1",
        smallWindTurbine: "Small Wind Turbine",
        tallPlatform: "Tall Platform",
        tallStorage: "Tall Storage",
        drillStrength1: "Drill Strength 1",
        exoRequestPlatform: "Exo Request Platform",
        largeWindTurbine: "Large Wind Turbine",
        largePlatformC: "Large Platform C",
        largeCurvedPlatform: "Large Curved Platform",
        largeStorage: "Large Storage",
        xlWindTurbine: "XL Wind Turbine",
        extraLargePlatformA: "Extra Large Platform A",
        extraLargeCurvedPlatform: "Extra Large Curved Platform",
        extraLargeStorage: "Extra Large Storage",
        mediumShuttle: "Medium Shuttle",
        largeShuttle: "Large Shuttle",
        worklight: "Worklight",
        smallSolarPanel: "Small Solar Panel",
        extenders: "Extenders",
        mediumSolarPanel: "Medium Solar Panel",
        powerSensor: "Power Sensor",
        solarArray: "Solar Array",
        oxygenTank: "Oxygen Tank",

        mediumResourceCanister: "Medium Resource Canister",
        mediumFluidSoilCanister: "Medium Fluid & Soil Canister",
        mediumGasCanister: "Medium Gas Canister",
        largeResourceCaniester: "Large Resource Caniester",
        largeSolarPanel: "Large Solar Panel",
        mediumShredder: "Medium Shredder",
        largeShredder: "Large Shredder",
        extraLargePlatformB: "Extra Large Platform B",
        extraLargePlatformC: "Extra Large Platform C",
        figurinePlatform: "Figurine Platform",
        crane: "Crane",
        largeResourceCanister: "Large Resource Canister",
        mediumStorageSilo: "Medium Storage Silo",
        floodlight: "Floodlight",
        powerCells: "Power Cells",
        wideMod: "Wide Mod",
        alignmentMod: "Alignment Mod",
        inhibitorMod: "Inhibitor Mod",
        boostMod: "Boost Mod",
        narrowMod: "Narrow Mod",
        terrainAnalyzer: "Terrain Analyzer",
        smallBattery: "Small Battery",
        batterySensor: "Battery Sensor",
        buttonRepeater: "Button Repeater",
        proximityRepeater: "Proximity Repeater",
        delayRepeater: "Delay Repeater",
        countRepeater: "Count Repeater",
        recreationalSphere: "Recreational Sphere",
        largeRover: "Large Rover",
        paver: "Paver",
        drillMod3: "Drill Mod 3",

        drillStrength3: "Drill Strength 3",
        fireworks: "Fireworks",
        fieldShelter: "Field Shelter",
        portableOxygenator: "Portable Oxygenator",
        holographicFigurine: "Holographic Figurine",
        mediumRover: "Medium Rover",
        shelter: "Shelter",
        winch: "Winch",
        autoExtractor: "Auto Extractor",
        probeScanner: "Probe Scanner",
        hydrazineThruster: "Hydrazine Thruster",
        largeStorageSiloA: "Large Storage Silo A",
        largeStorageSiloB: "Large Storage Silo B",
        extraLargeShredder: "Extra Large Shredder",
        drillStrength2: "Drill Strength 2",
        hydrazineJetPack: "Hydrazine Jet Pack",
        drillMod2: "Drill Mod 2",
        mediumTPlatform: "Medium T-Platform",
        mediumBuggyHorn: "Medium Buggy Horn",
        smallCanister: "Small Canister",
        powerSwitch: "Power Switch",
        automoton001: "Automoton 001",
        automoton002: "Automoton 002",
        cubicObject: "Cubic Object",
        stellarObject: "Stellar Object",
        cosmigBauble: "Cosmig Bauble",
        scrap: "Scrap",
        event: "Event",
        full: "Full",

        levelingBlock: "Leveling Block",
        unlocked: "Unlocked",
        smallCamera: "Small Camera",
        smallTrumpetHorn: "Small Trumpet Horn",
        hoverboard: "Hoverboard",
        largeExtendedPlatform: "Large Extended Platform",
        largeActiveStorage: "Large Active Storage",
        largeFogHorn: "Large Fog Horn",
        vtol: "VTOL",
        sourceVtol: "Vertical Take-Off and Landing (VTOL)",
        printTitle: "Print the Items",
        xlExtendedPlatform: "XL Extended Platform",
        sourcePortableSmeltingFurnace: "Portable Smelting Furnace",
        gravityGlobe: "Gravity Globe",
        easy: "Easy",
        planetDetails: "Planet Details",
        size: "Size",
        medium: "Medium",
        difficulty: "Difficulty",
        dayNigthCycle: "Day/Night cycle",
        minutes: "Minutes",
        sunPower: "Sun Power",
        windPower: "Wind Power",
        location: "Location: ",
        caveLayer: "Cave Layer",
        mantleLayer: "Mantle Layer",
        small: "Small",
        grayPlains: "Gray Plains",
        veryHigh: "Very High",
        low: "Low",
        high: "High",
        veryLow: "Very Low",
        purpleHills: "Purple Hills",
        mountains: "Mountains",
        icePlains: "Ice Plains",
        hard: "Hard",
        veryHard: "Very Hard",

        // Long Names
        backpackPrinter: "Backpack Printer",
        smallPrinter: "Small Printer",
        mediumPrinter: "Medium Printer",
        largePrinter: "Large Printer",
        soilCentrifuge: "Soil Centrifuge",
        chemistryLab: "Chemistry Lab",
        atmosphericCondenser: "Atmospheric Condenser",
        tradePlatform: "Trade Platform",
        smeltingFurnace: "Smelting Furnace",

        // Printers table
        craftedAt: "Crafted At",
        recipe: "Recipe",
        unlockCost: "Unlock Cost",
        powerConsumption: "Power Consumption",
        "-": "-",

        //Railways
        railway: "Railway",
        missionReward: "Mission Reward",
        
        railEngine: "Rail Engine",
        details: "Details",
        railEngineUseLine1: "Rail Engines are used to transport items and resources using Rail Cars. They stop at any Rail Stations that are set to stop any or automated Rail Engines.",
        railEngineUseLine2: "Rail Engines may be triggered to start moving by automation items, such as the Proximity Repeater and Button Repeater. Rail Engines and Rail Cars will start moving in the direction they last traveled in, unless at a dead-end, in which they will move in the opposite direction instead.",
        railEngineUseLine3: "2 Rail engines on front and back will make it go faster (works with C.O.L.E)",
        railEngineDescriptionLine1: "Rail Engines are a railway item in Astroneer. They allow players to travel along rails, have two small Slots, and provide oxygen to the player. Connecting to Rail Cars will increase the rail car's speed. Connecting more than 1 Rail Engine to a Rail Car will not increase the speed of the train.",
        
        railCar: "Rail Car",
        railCarDescriptionLine1: "Rail Cars are a railway item in Astroneer. They allows for transporting items and resources along rail lines, with a large slot and can form a train with Rail Cars, Rail Engines, or C.O.L.E.s.",
        railCarUseLine1: "Rail Cars are used to carry items and resources along rail lines and to connected Rail Stations. Rail Cars can form a train (with up to 6 parts) by being placed on a rail, and then attaching additional cars, or a Rail Engine or C.O.L.E.. Rail Cars can move on their own, but an engine will make it move faster.",
        
        railStation: "Rail Station",
        railStationDescriptionLine1: "Rail Stations are a Railway item in Astroneer. They allow Rail Cars to stop, load, or unload their cargo, as well as calling railway vehicles to the station",
        railStationUseLine1: "Rail Stations are used mainly as stops for Rail Cars and Rail Engines, which allow for the loading and unloading of items and resources. The control panel on the station's platform allows the player to change the stop and loading modes and can call rail vehicles.",
        railStationUseLine2: "Stop mode allows the station to stop no rail vehicles, stop only uncalled rail vehicles (those automated from other locations or piloted by the player), or to stop all rail vehicles.",
        railStationUseLine3: "Loading mode allows the station to load items to storages on rail cars or unload items to storages on the station platform. When in loading mode, Rail Cars that stop at a station will have all slots filled on the car's storage. When arriving at an unload station, all storages will be emptied from the rail cars, if enough space is available.",
        railStationUseLine4: "Rail Stations have two Target Pins and two Pin Slots, allowing for more controlled automation. Target Pins will send a signal to any connected items when a rail vehicle passes through or stops at the station. When a signal is sent to the Pin Slots, the station will send rail vehicles out the side of the station of the slot that was activated.",
        railStationUseLine5: "Attaching a Target Pin from Sensors or Repeaters directly on the station will call rail vehicles to it.",
        railStationUseLine6: "Rail Stations have a slot next to the control panel meant for a Beacon to be placed on to.",
        
        railPost: "Rail Post",
        railPostDescriptionLine1: "The Rail Post is a railway item in Astroneer. It allows for the creation of rail lines, and can be used to recall Rail Engines to it. It can also be used as an “extended Extender”, being able to channel power and O2 between bases. It has 2 small slots which can be useful for putting a Worklight with Power Sensor in it.",
        railPostUseLine1: "Rail Posts are placed from a Rail Post Bundle.",
        railPostUseLine2: "Placing a Rail Post within range of another will connect a rail line between them, deforming any terrain that might be in the way.",
        railPostUseLine3: "Rail Posts may be placed on any terrain, allowing for placement on walls and ceilings of caves.",
        railPostUseLine4: "The maximum placement distance for the post is shown as a coloured dial on the base of the post when placing.",
        railPostUseLine5: " - White indicates valid placement, below the maximum rail length.",
        railPostUseLine6: " - Blue indicates valid placement at optimal rail length.",
        railPostUseLine7: " - Pink indicates invalid placement -- whether from being placed too far, too close, or from creating too sharp of a turn.",
        
        railPostBundle: "Rail Post Bundle",
        railPostBundleDescriptionLine1: "Rail Post Bundles are a railway item in Astroneer. They are a bundle of 10 Rail Posts, and can be placed in the backpack's Aux Slots for easy placement of rail posts.",
        railPostBundleUseLine1: "Rail Post Bundles are used to place Rail Posts on terrain to expand the rail lines. The bundles may be placed in the Backpack's aux slots, which allows for quicker placement by pressing the context keys (PC: C or V).",
        
        tallRailPost: "Tall Rail Post",
        tallRailPostDescriptionLine1: "Tall Rail Posts are a railway item in Astroneer. They allow for the creation of rail lines, and can be used to recall Rail Engines to it. They are a tall version of Rail Posts, allowing for taller sections of rails.",
        tallRailPostUseLine1: "Tall Rail Posts are placed from a Tall Rail Post Bundle.",
        tallRailPostUseLine2: "Placing a Tall Rail Post within range of another will connect a rail line between them, deforming any terrain that might be in the way.",
        tallRailPostUseLine3: "Tall Rail Posts may be placed on any terrain, allowing for placement on walls and ceilings of caves.",
        tallRailPostUseLine4: "The maximum placement distance for the post is shown as a coloured dial on the base of the post when placing.",
        tallRailPostUseLine5: " - White indicates valid placement, below the maximum rail length",
        tallRailPostUseLine6: " - Blue indicates valid placement at optimal rail length",
        tallRailPostUseLine7: " - Pink indicates invalid placement -- whether from being placed too far, too close, or from creating too sharp of a turn.",
        
        tallRailPostBundle: "Tall Rail Post Bundle",
        tallRailPostBundleDescriptionLine1: "Tall Rail Post Bundles are a railway item in Astroneer. They are a bundle of 10 Tall Rail Posts.",
        tallRailPostBundleUseLine1: "Tall Rail Post Bundles are used to place Tall Rail Posts on terrain to expand the rail lines. The bundles may be placed in the Backpack's aux slots, which allows for quicker placement by pressing the context keys (PC: C or V).",
        
        railJunctions: "Rail Junctions",
        railJunctionDescriptionLine1: "Rail Junctions are a railway item in Astroneer. They allow for the creation of rail line junctions that splits rail lines in three directions. Each bundle contains 5 Rail Junctions and may be placed in the backpack's Aux Slots for easy placement of posts.",
        railJunctionUseLine1: "Rail Junction Bundles are used to place Rail Junctions on terrain to expand rail lines and change the direction of trains running along the line. The bundles may be placed in the Backpack's aux slots, which allows for quicker placement by pressing the context keys (PC: C or V).",
        railJunctionUseLine2: "Interacting with the Rail Junction will cause the rail connection to switch between the three possible states. When travelling on the rail line using a Rail Engine, Left and Right (PC: A and D) can be used to switch the junction direction, when the train is close enough to the junction.",
        railJunctionUseLine3: "Rail Junctions have three input slots for Automation signals, located between each of the three rail directions. Sending a signal to an automation input will connect the rail on either side of that input signal. Signals can also be sent anywhere on the junction itself, which would just cause the junction to cycle through the connections, similar to interacting with the junction manually.",
        railJunctionUseLine4: "Placing a Rail Junction within range of another Rail Post or Junction will connect a rail line between them, deforming any terrain that might be in the way.",
        railJunctionUseLine5: "Rail Junctions may be placed on any terrain, allowing for placement on walls and ceilings of caves.",
        railJunctionUseLine6: "The maximum placement distance for the junction is shown as a coloured dial on the base of the junction when placing.",
        railJunctionUseLine7: " - White indicates valid placement, below the maximum rail length",
        railJunctionUseLine8: " - Blue indicates valid placement at optimal rail length",
        railJunctionUseLine9: " - Pink indicates invalid placement -- whether from being placed too far, too close, or from creating too sharp of a turn.",
        
        railJunctionsBundle: "Rail Junctions Bundle",
        railJunctionBundleDescriptionLine1: "Rail Junction Bundles are a railway item in Astroneer. They are a bundle of 5 Rail Junctions, and may be placed in the backpack's Aux Slots for easy placement of posts.",
        railJunctionBundleUseLine1: "Rail Junction Bundles are used to place Rail Junctions on terrain to expand the rail lines. The bundles may be placed in the Backpack's aux slots, which allows for quicker placement by pressing the context keys (PC: C or V).",

        cole: "C.O.L.E",
        coleDescriptionLine1: "C.O.L.E. (Computer Operated Logistics Engines), are a railway item in Astroneer. They allow for travel along rails, has two small Slots, and provides oxygen to the player. They are faster than a Rail Engine and harmless.",
        coleUseLine1: "Rewarded from completing the Travelling Companion mission.",
        coleUseLine2: " - The front of C.O.L.E. has an animated face that changes depending on if it is empty, a player is sitting in it, or if it is moving with the player sitting in it.",
        coleUseLine3: " - Each save can only have one C.O.L.E per player.",
        coleUseLine4: " - C.O.L.E. is not craftable.",
        coleUseLine5: " - C.O.L.E. cannot be placed in storage unless packaged.",

        sitePylon: "Site Pylon",
        sitePylonDescriptionLine1: "Site Pylons are a railway item in Astroneer. They allow for the creation of rail lines, and can be used to recall Rail Engines to the Site Pylon. They spawn on Glacio and Calidor near mission items.",
        sitePylonUseLine1: "Site Pylons spawn on Glacio and Calidor near mission items, such as Freight Modules, Frozen Argon, Artifacts, and Obelisks.",
        sitePylonUseLine2: "Site Pylons will connect rail lines to any other pylon, Rail Post, Tall Rail Post, or Rail Junction. They are best used with Junctions, as the Site Pylons are a dead-end.",
        sitePylonUseLine3: "Site Pylons may be picked up and moved for better placement of rails. The Packager can be used on it for better transportation.",


        //Flora
        flora: "Flora",
        mountainSlopes: "Mountain Slopes",
        surface: "Surface",
        underground: "Underground",
        bouncevine: "Bouncevine",
        popcoral: "Popcoral",
        daggeroot: "Daggeroot",
        hissbine: "Hissbine",
        lashleaf: "Lashleaf",
        volatileCataplant: "Volatile Cataplant",
        thistlewhip: "Thistlewhip",
        volatileAttactus: "Volatile Attactus",
        elegantSpewflower: "Elegant Spewflower",
        wheezeweeds: "Wheezeweeds",
        noxiousCataplant: "Noxious Cataplant",
        spinyAttactus: "Spiny Attactus",
        spinelily: "Spinelily",
        noxiousSpewflower: "Noxious Spewflower",
        boomalloon: "Boomalloon",
        bouncevineSeed: "Bouncevine Seed",
        popcoralSeed: "Popcoral Seed",
        daggerootSeed: "Daggeroot Seed",
        hissbineSeed: "Hissbine Seed",
        lashleafSeed: "Lashleaf Seed",
        volatileCataplantSeed: "Volatile Cataplant Seed",
        thistlewhipSeed: "Thistlewhip Seed",
        volatileAttactusSeed: "Volatile Attactus Seed",
        elegantSpewflowerSeed: "Elegant Spewflower Seed",
        wheezeweedsSeed: "Wheezeweeds Seed",
        noxiousCataplantSeed: "Noxious Cataplant Seed",
        spinyAttactusSeed: "Spiny Attactus Seed",
        spinelilySeed: "Spinelily Seed",
        noxiousSpewflowerSeed: "Noxious Spewflower Seed",
        boomalloonSeed: "Boomalloon Seed",
        bouncevineDescription: "Bouncevines are a green plant with red vines, found on the surface of Sylva. When stepped on, the player will get launched up in the air. Since they mostly are found in the mountainous biome, the player could be launched high enough to be killed by fall damage.",
        popcoralDescription: "Popcoral can be found in abundance in caves and are mostly harmless. Upon digging with the Terrain Tool at their base they will explode. This explosion can be fatal if a player is standing too near, but they can be safely dug up from a distance.",
        daggerootDescription: "Daggeroot are a white plant with red spots, found mostly on Desolo, on the surface of Atrox and in the mantle layer of Sylva, and pose a danger to the player. Getting too close to the Daggeroot will cause them to release dangerous spikes around them which could kill the player in 2 hits.",
        hissbineDescription: "Hissbines are flora that generates underground on all planets. If the player gets too close, it will spray a cloud of acid at the player. There are three varieties: Normal, Vibrant, and Dull. The acid clouds from these varieties deal different amounts of damage, with Normal Hissbines being the least deadly, and Dull being the most dangerous. More difficult planets have more dangerous Hissbines.",
        leashleafDescription: "Lashleaves are flora with two leaves with a pink tongue-like leaf in the middle, found on Vesania and Novus. When the player steps on one, it will launch them into the air. Domestic Lashleaves will rotate 90 degrees counter-clockwise when they are finished growing.",
        volatileCataplantDescription1: "Cataplants are flora that has an arm with a red orb, with the base being colored.",
        volatileCataplantDescription2: "If the player gets in range, it will begin tossing the red orb at the player. After a couple of seconds the orb will then explode. The Cataplant will continue throwing orbs until the player moves away or is dead. Such orbs sometimes will clip through the terrain or deflect off slopes, rendering the player safe from the attack. ",
        volatileCataplantDescription3: "Volatile Cataplants can be found on Atrox and in groups of three on Glacio. If you are killed by the Volatile Cataplants, there is a chance some of your items are destroyed.",
        volatileCataplantDescription4: "Volatile Cataplants can be tricked into destroying themselves.",
        thistlewhipDescription: "Thistlewhips are plants that have a purple base with a long orange vine with a bulbous end, found on Vesania and Novus. When the player gets close enough, the vine will shake and produce pollen as a warning. When the player moves closer, it whips at the player with the vine.",
        volatileAttactusDescription1: "Attacti, plural of Attactus, are flora that generate on the surface and underground.",
        volatileAttactusDescription2: "If the player gets in range, it will activate and start spitting deadly projectiles at the player. When the projectile collides with terrain, it will give a small explosion and destroy a small portion of soil.",
        volatileAttactusDescription3: "The explosion from a Volatile Attactus can also destroy player's vehicles which makes Volatile Attacti quite dangerous for rovers or shuttles.",
        elegantSpewflowerDescription1: "Elegant Spewflowers are flora that generate on the surface of Atrox.",
        elegantSpewflowerDescription2: "If the player gets near, they will retract their umbrella-shaped leaf and begin to spew poison in a radius until the player dies or moves away from the plant. The player may stand on the edge of the poison cloud to observe the spewflowers in action.",
        wheezeweedDescription1: "Wheezeweeds are big, round yellow plants with holes revealing a red membrane, found on Atrox and Calidor.",
        wheezeweedDescription2: "When the player approaches them, they produce a wheezing sound and the membrane puffs out through the holes. If the player gets too close they rapidly puff up, knocking the player back a good distance.",
        noxiousCataplantDescription1: "Cataplants are flora that has an arm with a red orb, with the base being colored.",
        noxiousCataplantDescription2: "If the player gets in range, it will begin tossing the red orb at the player. After a couple of seconds the orb will then explode, making a cloud of gas. The Cataplant will continue throwing orbs until the player moves away or is dead. Such orbs sometimes will clip through the terrain or deflect off slopes, rendering the player safe from the attack.",
        noxiousCataplantDescription3: "Noxious Cataplants can be found on the surfaces and caves of Vesania and Novus",
        spinyAttactusDescription1: "Attacti, plural of Attactus, are flora that generate on the surface and underground",
        spinyAttactusDescription2: " If the player gets in range, it will activate and start spitting deadly projectiles at the player. When the projectile collides with terrain, it will explode into gas",
        spinelilyDescription1: "Spinelilies are spiky lilypads that can form in small clusters, found on Calidor and Atrox.",
        spinelilyDescription2: "When a player jumps on them it will launch them in the air, and may cause damage if launched too high.",
        noxiousSpewflowerDescription1: "Noxious Spewflowers are flora that generate on the underground of Atrox.",
        noxiousSpewflowerDescription2: "If the player gets near, they will retract their umbrella-shaped leaf and begin to spew poison in a radius until the player dies or moves away from the plant. The player may stand on the edge of the poison cloud to observe the spewflowers in action.",
        noxiousSpewflowerDescription3: "The poison clouds from Noxious Spewflowers do considerably more damage than those from Elegant Spewflowers.",
        boomalloonDescription1: "Boomalloons are flora that generates on the surface and caves of Glacio.",
        boomalloonDescription2: "If the player gets too close, they explode with a cloud of acid. They are similar to Popcoral, but these only require the player being near to explode.",
        boomalloonDescription3: "They have a hitbox that is used to detect if the player is close enough for it to explode, but this hitbox has some strange properties. The hitbox will prevent players from interacting with things in it such as scanning Research Samples, or dropping items in it.",
        boomalloonDescription4: "Boomalloons can be detonated safely simply by approaching them slowly, as their trigger radius is bigger than their blast radius.",
        boomalloonDescription5: "Boomalloon seeds take roughly a minute and 20 seconds to grow.",

        //Missions
        missions: "Missions",
}