export default {
        //App commun texts
        welcome: 'THE EASIER WAY\nTO USE\nTHE ASTROPEDIA',
        userIdentification: 'What is your\nAstroneer name?',
        language: 'Language: ',
        whatYouWant: 'Don\'t see what you want? ',
        contactUs: 'Contact Us',
        contactUsDefaultName: 'Astroneer Player',
        contactUsMail: 'noreply',
        contactUsMessageFrom: '\n\n\nMessage from: ',
        contactUsMessageReply: '\nReply to: ',
        contactUsWarnning: 'You need to include a message!',
        contactUsPlaceholderEmail: 'Email',
        contactUsPlaceholderName: 'Name',
        contactUsPlaceholderMessage: 'Message',
        avatar: 'Avatar: ',
        name: 'Name: ',
        aboutUs: 'About Us',
        aboutUsCredit: 'Credits',
        aboutUsDeveloped: 'Developed by MIDDLEWARE DEV',
        aboutUsDesign: 'Design',
        aboutUsThanks: 'With Special Thanks to',
        aboutUsTranslation: 'Translations',
        warningTitle: 'Warning',
        warningMessage: 'The changes only be effective after you restart the Astropedia',
        warningButton: 'Ok',

        //Titles
        mainTitle: 'Astropedia',
        planetsTitle: 'Planets',
        resourcesTitle: 'Resources',
        favoritesTitle: 'Favorites',
        naturalResourcesTitle: 'natural resources',
        atmosphericResourcesTitle: 'atmospheric resources',
        sourceTitle: 'Source',
        usesTitle: 'Uses',
        printers: 'Printers',

        //Planet's names
        sylva: 'Sylva',
        desolo: 'Desolo',
        calidor: 'Calidor',
        vesania: 'Vesania',
        novus: 'Novus',
        glacio: 'Glacio',
        atrox: 'Atrox',

        //Resource's names
        ammonium: 'Ammonium',
        astronium: 'Astronium',
        clay: 'Clay',
        compound: 'Compound',
        graphite: 'Graphite',
        hematite: 'Hematite',
        laterite: 'Laterite',
        lithium: 'Lithium',
        malachite: 'Malachite',
        organic: 'Organic',
        quartz: 'Quartz',
        resin: 'Resin',
        sphalerite: 'Sphalerite',
        titanite: 'Titanite',
        wolframite: 'Wolframite',
        aluminum: 'Aluminum',
        carbon: 'Carbon',
        ceramic: 'Ceramic',
        copper: 'Copper',
        glass: 'Glass',
        iron: 'Iron',
        titanium: 'Titanium',
        tungsten: 'Tungsten',
        zinc: 'Zinc',
        argon: 'Argon',
        helium: 'Helium',
        hydrogen: 'Hydrogen',
        methane: 'Methane',
        nitrogen: 'Nitrogen',
        sulfur: 'Sulfur',
        aluminumAlloy: 'Aluminum A...',
        diamond: 'Diamond',
        explosivePowder: 'Explosive P...',
        hydrazine: 'Hydrazine',
        graphene: 'Graphene',
        nanocarbonAlloy: 'Nanocarbon A.',
        plastic: 'Plastic',
        rubber: 'Rubber',
        silicone: 'Silicone',
        steel: 'Steel',
        titaniumAlloy: 'Titanium Alloy',
        tungstenCarbide: 'Tungsten C...',

        //Sources and Items name
        sourceAllPlanets: 'All Planets',
        solidFuelThruster: 'Solid-Fuel Thruster',
        exoChip: 'Exo Chip',
        packager: 'Packager',
        solidFuelJumpJet: 'Solid-Fuel Jump Jet',
        dynamite: 'Dynamite',
        smallGenerator: 'Small Generator',
        tether: 'Tether',
        roverSeat: 'Rover Seat',
        trailer: 'Trailer',
        researchChamber: 'Research Chamber',
        largeRoverSeat: 'Large Rover Seat',
        buggy: 'Buggy',
        splitter: 'Splitter',
        autoArm: 'Auto Arm',
        mediumBattery: 'Medium Battery',
        rtg: 'RTG',
        glowsticks: 'Glowsticks',
        beacon: 'Beacon',
        storageSensor: 'Storage Sensor',
        mediumSensorArch: 'Medium Sensor Arch',
        largeSensorRing: 'Large Sensor Ring',
        largeSensorHoopA: 'Large Sensor Hoop A',
        largeSensorHoopB: 'Large Sensor Hoop B',
        xlSensorArch: 'Xl Sensor Arch',
        xlSensorCanopy: 'Xl Sensor Canopy',
        xlSensorHoopA: 'Xl Sensor Hoop A',
        xlSensorHoopB: 'Xl Sensor Hoop B',
        canister: 'Canister',
        oxygenFilter: 'Oxygen Filter',
        mediumStorage: 'Medium Storage',
        mediumPlatformA: 'Medium Platform A',
        mediumPlatformB: 'Medium Platform B',
        mediumPlatformC: 'Medium Platform C',
        largePlatformA: 'Large Platform A',
        largePlatformB: 'Large Platform B',
        oxygenator: 'Oxygenator',
        mediumGenerator: 'Medium Generator',
        mediumWindTurbine: 'Medium Wind Turbine',
        tractor: 'Tractor',
        largeTPlatform: 'Large T-Platform',
        smallShuttle: 'Small Shuttle',
        landingPad: 'Landing Pad',
        sourceAluminumAlloy: 'Aluminum Alloy',
        sourceExplosivePowder: 'Explosive Powder',
        sourceNanocarbonAlloy: 'Nanocarbon Alloy',
        sourceTungstenCarbide: 'Tungsten Carbide',
        drillMod1: 'Drill Mod 1',
        smallWindTurbine: 'Small Wind Turbine',
        tallPlatform: 'Tall Platform',
        tallStorage: 'Tall Storage',
        drillStrength1: 'Drill Strength 1',
        exoRequestPlatform: 'Exo Request Platform',
        largeWindTurbine: 'Large Wind Turbine',
        largePlatformC: 'Large Platform C',
        largeCurvedPlatform: 'Large Curved Platform',
        largeStorage: 'Large Storage',
        xlWindTurbine: 'Xl Wind Turbine',
        extraLargePlatformA: 'Extra Large Platform A',
        extraLargeCurvedPlatform: 'Extra Large Curved Platform',
        extraLargeStorage: 'Extra Large Storage',
        mediumShuttle: 'Medium Shuttle',
        largeShuttle: 'Large Shuttle',
        worklight: 'Worklight',
        smallSolarPanel: 'Small Solar Panel',
        extenders: 'Extenders',
        mediumSolarPanel: 'Medium Solar Panel',
        powerSensor: 'Power Sensor',
        solarArray: 'Solar Array',
        oxygenTank: 'Oxygen Tank',
        mediumResourceCanister: 'Medium Resource Canister',
        mediumFluidSoilCanister: 'Medium Fluid & Soil Canister',
        mediumGasCanister: 'Medium Gas Canister',
        largeResourceCaniester: 'Large Resource Caniester',
        largeSolarPanel: 'Large Solar Panel',
        mediumShredder: 'Medium Shredder',
        largeShredder: 'Large Shredder',
        extraLargePlatformB: 'Extra Large Platform B',
        extraLargePlatformC: 'Extra Large Platform C',
        figurinePlatform: 'Figurine Platform',
        crane: 'Crane',
        largeResourceCanister: 'Large Resource Canister',
        mediumStorageSilo: 'Medium Storage Silo',
        floodlight: 'Floodlight',
        powerCells: 'Power Cells',
        wideMod: 'Wide Mod',
        alignmentMod: 'Alignment Mod',
        inhibitorMod: 'Inhibitor Mod',
        boostMod: 'Boost Mod',
        narrowMod: 'Narrow Mod',
        terrainAnalyzer: 'Terrain Analyzer',
        smallBattery: 'Small Battery',
        batterySensor: 'Battery Sensor',
        buttonRepeater: 'Button Repeater',
        proximityRepeater: 'Proximity Repeater',
        delayRepeater: 'Delay Repeater',
        countRepeater: 'Count Repeater',
        recreationalSphere: 'Recreational Sphere',
        largeRover: 'Large Rover',
        paver: 'Paver',
        drillMod3: 'Drill Mod 3',
        drillStrength3: 'Drill Strength 3',
        fireworks: 'Fireworks',
        fieldShelter: 'Field Shelter',
        portableOxygenator: 'Portable Oxygenator',
        holographicFigurine: 'Holographic Figurine',
        mediumRover: 'Medium Rover',
        shelter: 'Shelter',
        winch: 'Winch',
        autoExtractor: 'Auto Extractor',
        probeScanner: 'Probe Scanner',
        hydrazineThruster: 'Hydrazine Thruster',
        largeStorageSiloA: 'Large Storage Silo A',
        largeStorageSiloB: 'Large Storage Silo B',
        extraLargeShredder: 'Extra Large Shredder',
        drillStrength2: 'Drill Strength 2',
        hydrazineJetPack: 'Hydrazine Jet Pack',
        drillMod2: 'Drill Mod 2',
        mediumTPlatform: 'Medium T-Platform',
        mediumBuggyHorn: 'Medium Buggy Horn',
        smallCanister: 'Small Canister',
        powerSwitch: 'Power Switch',
        automoton001: 'Automoton 001',
        automoton002: 'Automoton 002',
        cubicObject: 'Cubic Object',
        stellarObject: 'Stellar Object',
        cosmigBauble: 'Cosmig Bauble',
        scrap: 'Scrap',
        event: 'Event',
        full: 'Full',
        levelingBlock: 'Leveling Block',
        unlocked: 'Unlocked',
        smallCamera: 'Small Camera',
        smallTrumpetHorn: 'Small Trumpet Horn',
        hoverboard: 'Hoverboard',
        largeExtendedPlatform: 'Large Extended Platform',
        largeActiveStorage: 'Large Active Storage',
        largeFogHorn: 'Large Fog Horn',
        vtol: 'VTOL',
        sourceVtol: 'Vertical Take-Off and Landing (VTOL)',
        printTitle: 'Print the Items',
        xlExtendedPlatform: 'XL Extended Platform',
        sourcePortableSmeltingFurnace: 'Portable Smelting Furnace',
        gravityGlobe: 'Gravity Globe',
        easy: 'Easy',
        planetDetails: 'Planet Details',
        size: 'Size',
        medium: 'Medium',
        difficulty: 'Difficulty',
        dayNigthCycle: 'Day/Nigth cycle',
        minutes: 'Minutes',
        sunPower: 'Sun Power',
        windPower: 'Wind Power',
        location: 'Location: ',
        caveLayer: 'Cave Layer',
        mantleLayer: 'Mantle Layer',
        small: 'Small',
        grayPlains: 'Gray Plains',
        veryHigh: 'Very High',
        low: 'Low',
        high: 'High',
        veryLow: 'Very Low',
        purpleHills: 'Purple Hills',
        mountains: 'Mountains',
        icePlains: 'Ice Plains',
        hard: 'Hard',
        veryHard: 'Very Hard',

        // Long Names
        backpackPrinter: 'Backpack',
        smallPrinter: 'Small Printer',
        mediumPrinter: 'Medium Printer',
        largePrinter: 'Large Printer',
        soilCentrifuge: 'Soil Centrifuge',
        chemistryLab: 'Chemistry Lab',
        atmosphericCondenser: 'Atmospheric Condenser',
        tradePlatform: 'Trade Platform',
        smeltingFurnace: 'Smelting Furnace',
        
        backpack: 'Backpack',
        sourceSmallPrinter: 'Small Printer',
        sourceMediumPrinter: 'Medium Printer',
        sourceLargePrinter: 'Large Printer',
        sourceChemistryLab: 'Chemistry Lab',
        sourceSoilCentrifuge: 'Soil Centrifuge',
        sourceAtmosphericCondenser: 'Atm... Conden...',
        sourceTradePlatform: 'Plat. de Troca',
        sourceSmeltingFurnace: 'Sme... Furnace',
}