export default {
    //App commun texts
    welcome: 'LA MANERA MÁS FÁCIL DE USAR nEL ASTROPEDÍA',
    userIdentification: '¿Cuál es su nombre nAstroneer?',
    language: 'Idioma: ',
    whatYouWant: '¿No ves lo que quieres? ',
    contactUs: 'Contáctenos',
    contactUsDefaultName: 'Astroneer Player',
    contactUsMail: 'noreply',
    contactUsMessageFrom: '\n\n\nMensaje de: ',
    contactUsMessageReply: '\nResponder a: ',
    contactUsWarnning: 'Tienes que incluir un mensaje!',
    contactUsPlaceholderEmail: 'Email',
    contactUsPlaceholderName: 'Nombre',
    contactUsPlaceholderMessage: 'Mensaje',
    avatar: 'Avatar: ',
    name: 'Nombre: ',
    aboutUs: 'Sobre nosotros',
    aboutUsCredit: 'Créditos',
    aboutUsDeveloped: 'Desarrollada por MIDDLEWARE DEV',
    aboutUsDesign: 'Diseño',
    aboutUsThanks: 'Con agradecimiento especial a',
    warningTitle: 'Aviso',
    warningMessage: 'Los cambios solo serán efectivos después de reiniciar el Astropedía',
    warningButton: 'Ok',

    //Titles
    mainTitle: 'Astropedía',
    planetsTitle: 'Planetas',
    resourcesTitle: 'Recursos',
    favoritesTitle: 'Favoritos',
    naturalResourcesTitle: 'Recursos Naturales',
    atmosphericResourcesTitle: 'Recursos Atmosféricos',
    sourceTitle: 'Obtenido de',
    usesTitle: 'Usos',

    //Planet's names
    sylva: 'Sylva',
    desolo: 'Desolo',
    calidor: 'Calidor',
    vesania: 'Vesania',
    novus: 'Novus',
    glacio: 'Glacio',
    atrox: 'Atrox',

    //Resource's names
    ammonium: 'Amoníaco',
    astronium: 'Astronio',
    clay: 'Arcilla',
    compound: 'Compuesto',
    graphite: 'Grafito',
    hematite: 'Hematites',
    laterite: 'Laterita',
    lithium: 'Litio',
    malachite: 'Malaquita',
    organic: 'Orgánico',
    quartz: 'Cuarzo',
    resin: 'Resina',
    sphalerite: 'Esfalerita',
    titanite: 'Titanita',
    wolframite: 'Wolframita',
    aluminum: 'Aluminio',
    carbon: 'Carbón',
    ceramic: 'Cerámica',
    copper: 'Cobre',
    glass: 'Vidrio',
    iron: 'Hierro',
    titanium: 'Titanio',
    tungsten: 'Tungsteno',
    zinc: 'Cinc',
    argon: 'Argón',
    helium: 'Helio',
    hydrogen: 'Hidrógeno',
    methane: 'Metano',
    nitrogen: 'Nitrógeno',
    sulfur: 'Azufre',
    aluminumAlloy: 'Al. de Aluminio',
    diamond: 'Diamante',
    explosivePowder: 'P. Explosivo',
    hydrazine: 'Hidracina',
    graphene: 'Grafeno',
    nanocarbonAlloy: 'Al. de Nanocar',
    plastic: 'Plastico',
    rubber: 'Caucho',
    silicone: 'Silicona',
    steel: 'Acero',
    titaniumAlloy: 'Al. de titanio',
    tungstenCarbide: 'Carb. de Tungs.',

    //Sources and Items name
    sourceAllPlanets: 'Todos los Planetas',
    soilCentrifuge: 'Centrífuga de Suelo',
    tradePlatform: 'Plataforma de Comercio',
    smallPrinter: 'Pequeña Impresora',
    solidFuelThruster: 'Motor de Combustible Sólido',
    chemistryLab: 'Laboratorio de Química',
    exoChip: 'Chip Exo',
    packager: 'Envasador',
    solidFuelJumpJet: 'Propulsor de Combustible Sólido',
    dynamite: 'Dinamita',
    smeltingFurnace: 'Horno de Fundición',
    backpackPrinter: 'Impresora de Mochila',
    smallGenerator: 'Pequeño Generador',
    tether: 'Cables',
    roverSeat: 'Asiento del vehículo',
    mediumPrinter: 'Impresora Mediana',
    trailer: 'Tráiler',
    researchChamber: 'Cámara de Investigación',
    largePrinter: 'Impresora Grande',
    largeRoverSeat: 'Asiento Grande de Vehículo',
    buggy: 'Buggy',
    splitter: 'Divisor',
    autoArm: 'Brazo Mecanico',
    mediumBattery: 'Bateria Mediana',
    rtg: 'RTG',
    glowsticks: 'Luces Químicas',
    beacon: 'Señal',
    storageSensor: 'Sensor de Depósito',
    mediumSensorArch: 'Sensor de Arco Medio',
    largeSensorRing: 'Sensor de Anillo Grande',
    largeSensorHoopA: 'Sensor en Aro Grande A',
    largeSensorHoopB: 'Sensor en Aro Grande B',
    xlSensorArch: 'Sensor en Arco GG',
    xlSensorCanopy: 'Sensor de Dosel GG',
    xlSensorHoopA: 'Sensor en Aro GG A',
    xlSensorHoopB: 'Sensor en Aro GG B',
    canister: 'Contenedor pequeño',
    oxygenFilter: 'Filtros de Oxígeno',
    mediumStorage: 'Almacenamiento promedio',
    mediumPlatformA: 'Plataforma Mediana A',
    mediumPlatformB: 'Plataforma Mediana B',
    mediumPlatformC: 'Plataforma Mediana C',
    largePlatformA: 'Plataforma Grande A',
    largePlatformB: 'Plataforma Grande B',
    oxygenator: 'Oxigenador',
    mediumGenerator: 'Generador Mediano',
    mediumWindTurbine: 'Turbina de Viento Mediana',
    tractor: 'Tractor',
    largeTPlatform: 'Plataforma-T Grande',
    smallShuttle: 'Pequeño Transbordador',
    landingPad: 'Pista de Aterrizaje',
    sourceAluminumAlloy: 'Aleación de aluminio',
    sourceExplosivePowder: 'Polvo explosivo',
    sourceNanocarbonAlloy: 'Nano-carbón',
    sourceTungstenCarbide: 'Carburo de tungsteno',
    drillMod1: 'Mod. de Taladro 1',
    smallWindTurbine: 'Turbina de Viento Pequeña',
    tallPlatform: 'Plataforma Alta',
    tallStorage: 'Almacenamiento Alto',
    drillStrength1: 'Fuerza de Perforación 1',
    exoRequestPlatform: 'Plataforma de Solicitud EXO',
    largeWindTurbine: 'Turbina de Viento Grande',
    largePlatformC: 'Plataforma Grande C',
    largeCurvedPlatform: 'Large Curved Platform',
    largeStorage: 'Plataforma Grande Curva',
    xlWindTurbine: 'Turbina de Viento GG',
    extraLargePlatformA: 'Plataforma Extra Grande A',
    extraLargeCurvedPlatform: 'Plataforma Extra Grande Curva',
    extraLargeStorage: 'Almacenamiento Extra Grande',
    mediumShuttle: 'Transbordador Mediano',
    largeShuttle: 'Transbordador Grande',
    worklight: 'Luz de Trabajo',
    smallSolarPanel: 'Solar Pequeño',
    extenders: 'Extensores',
    mediumSolarPanel: 'Solar Mediano',
    powerSensor: 'Sensor de Energía',
    solarArray: 'Panel solar',
    oxygenTank: 'Tanque de Oxígeno',
    mediumResourceCanister: 'Contenedor de Recursos Mediano',
    mediumFluidSoilCanister: 'Contenedor de Suelo y Líquido Mediano',
    mediumGasCanister: 'Contenedor de Gas Mediano',
    atmosphericCondenser: 'Condensador Atmosférico',
    largeResourceCaniester: 'Contenedor Grande de Recursos',
    largeSolarPanel: 'Panel Solar Grande',
    mediumShredder: 'Trituradora Mediana',
    largeShredder: 'Trituradora Grande',
    extraLargePlatformB: 'Plataforma Extra Grande B',
    extraLargePlatformC: 'Plataforma Extra Grande C',
    figurinePlatform: 'Plataforma de Figurilla',
    crane: 'Grua',
    largeResourceCanister: 'Contenedor de Recursos Grande',
    mediumStorageSilo: 'Silo Mediano',
    floodlight: 'Luz de Inundación',
    powerCells: 'Células de Energía',
    wideMod: 'Mod Amplio',
    alignmentMod: 'Modificador de Alineación',
    inhibitorMod: 'Inhibidor',
    boostMod: 'Mod de Velocidad',
    narrowMod: 'Mod de Estrecho',
    terrainAnalyzer: 'Analizador de Terreno',
    smallBattery: 'Batería Pequeña',
    batterySensor: 'Sensor de batería',
    buttonRepeater: 'Repetidor de Botón',
    proximityRepeater: 'Repetidor de Proximidad',
    delayRepeater: 'Repetidor de Retardo',
    countRepeater: 'Recuento',
    recreationalSphere: 'Esfera Recreativa',
    largeRover: 'Cuatriciclo Grande',
    paver: 'Adoquín',
    drillMod3: 'Mod de Taladro 3',
    drillStrength3: 'Fuerza de Perforación 3',
    fireworks: 'Fuegos Artificiales',
    fieldShelter: 'Refugio de Campo',
    portableOxygenator: 'Oxigenador Portátil',
    holographicFigurine: 'Estatuilla Holográfica',
    mediumRover: 'Cuatriciclo Mediano',
    shelter: 'Refugio',
    winch: 'Cabrestante',
    autoExtractor: 'Extractor Automático',
    probeScanner: 'Lector de Sonda',
    hydrazineThruster: 'Propulsor de Hidracina',
    largeStorageSiloA: 'Silo Grande A',
    largeStorageSiloB: 'Silo Grande B',
    extraLargeShredder: 'Trituradora Extra Grande',
    drillStrength2: 'Fuerza de Perforación 2',
    hydrazineJetPack: 'Propulsor de Chorro de Hidracina',
    drillMod2: 'Mod de Taladro 2'
}