export default {
    //App commun texts
    welcome: "LA MANERA MÁS FÁCIL\nDE USAR\nLA ASTROPEDIA",
    userIdentification: "¿Cuál es tu\nnombre de Astroneer?",
    language: "Idioma: ",
    whatYouWant: "¿No ves lo que quieres?",
    contactUs: "Contáctanos",
    contactUsDefaultName: "Jugador de Astroneer",
    contactUsMail: "noreply",
    contactUsMessageFrom: "\n\n\nMensaje de: ",
    contactUsMessageReply: "\nResponder a: ",
    contactUsWarning: "¡Necesitas incluir un mensaje!",
    contactUsPlaceholderEmail: "Correo electrónico",
    contactUsPlaceholderName: "Nombre",
    contactUsPlaceholderMessage: "Mensaje",
    avatar: "Avatar: ",
    name: "Nombre: ",
    aboutUs: "Sobre Nosotros",
    aboutUsCredit: "Créditos",
    aboutUsDeveloped: "Desarrollado por MIDDLEWARE DEV",
    aboutUsDesign: "Diseño",
    aboutUsThanks: "Con Agradecimientos Especiales a",
    aboutUsTranslation: "Traducciones",
    warningTitle: "Advertencia",
    warningMessage: "Los cambios solo se aplicarán después de que reinicies la Astropedia",
    warningButton: "Aceptar",

    //Titles
    mainTitle: "Astropedia",
    planetsTitle: "Planetas",
    resourcesTitle: "Recursos",
    favoritesTitle: "Favoritos",
    naturalResourcesTitle: "Recursos Naturales",
    atmosphericResourcesTitle: "Recursos Atmosféricos",
    sourceTitle: "Fuente",
    usesTitle: "Usos",
    printers: "Impresoras",
    settings: "Configuración",

    //Planet's names
    sylva: "Sylva",
    desolo: "Desolo",
    calidor: "Calidor",
    vesania: "Vesania",
    novus: "Novus",
    glacio: "Glacio",
    atrox: "Atrox",

    //Basic Resource's names
    ammonium: "Amonio",
    astronium: "Astronio",
    clay: "Arcilla",
    compound: "Compuesto",
    graphite: "Grafito",
    hematite: "Hematita",
    laterite: "Laterita",
    lithium: "Litio",
    malachite: "Malaquita",
    organic: "Orgánico",
    quartz: "Cuarzo",
    resin: "Resina",
    sphalerite: "Esfalerita",
    titanite: "Titanita",
    wolframite: "Wolframita",
    aluminum: "Aluminio",
    carbon: "Carbono",
    ceramic: "Cerámica",
    copper: "Cobre",
    glass: "Vidrio",
    iron: "Hierro",
    titanium: "Titanio",
    tungsten: "Tungsteno",
    zinc: "Zinc",

    //Gas names
    argon: "Argón",
    helium: "Helio",
    hydrogen: "Hidrógeno",
    methane: "Metano",
    nitrogen: "Nitrógeno",
    sulfur: "Azufre",

    //Compost Resourse name
    aluminumAlloy: "Aleación de Aluminio",
    diamond: "Diamante",
    explosivePowder: "Polvo Explosivo",
    hydrazine: "Hidracina",
    graphene: "Grafeno",
    nanocarbonAlloy: "Aleación de Nanocarbono",
    plastic: "Plástico",
    rubber: "Caucho",
    silicone: "Silicona",
    steel: "Acero",
    titaniumAlloy: "Aleación de Titanio",
    tungstenCarbide: "Carburo de Tungsteno",

    //Sources and Items name
    sourceAllPlanets: "Todos los Planetas",
    solidFuelThruster: "Propulsor de Combustible Sólido",
    exoChip: "Exo Chip",
    packager: "Empaquetador",
    solidFuelJumpJet: "Propulsor de Combustible Sólido",
    dynamite: "Dinamita",
    smallGenerator: "Generador Pequeño",
    tether: "Anclaje",
    roverSeat: "Asiento de Rover",
    trailer: "Remolque",
    researchChamber: "Cámara de Investigación",
    largeRoverSeat: "Asiento Grande de Rover",
    buggy: "Buggy",
    splitter: "Divisor",
    autoArm: "Brazo Automático",
    mediumBattery: "Batería Mediana",
    rtg: "RTG",
    glowsticks: "Bastones Luminosos",
    beacon: "Baliza",

    storageSensor: "Sensor de Almacenamiento",
    mediumSensorArch: "Arco de Sensor Mediano",
    largeSensorRing: "Anillo de Sensor Grande",
    largeSensorHoopA: "Aro de Sensor Grande A",
    largeSensorHoopB: "Aro de Sensor Grande B",
    xlSensorArch: "Arco de Sensor XL",
    xlSensorCanopy: "Toldo de Sensor XL",
    xlSensorHoopA: "Aro de Sensor XL A",
    xlSensorHoopB: "Aro de Sensor XL B",
    canister: "Contenedor",
    oxygenFilter: "Filtro de Oxígeno",
    mediumStorage: "Almacenamiento Mediano",
    mediumPlatformA: "Plataforma Mediana A",
    mediumPlatformB: "Plataforma Mediana B",
    mediumPlatformC: "Plataforma Mediana C",
    largePlatformA: "Plataforma Grande A",
    largePlatformB: "Plataforma Grande B",
    oxygenator: "Oxigenador",
    mediumGenerator: "Generador Mediano",
    mediumWindTurbine: "Turbina Eólica Mediana",
    tractor: "Tractor",

    largeTPlatform: "Gran Plataforma T",
    smallShuttle: "Nave Pequeña",
    landingPad: "Plataforma de Aterrizaje",
    drillMod1: "Modificación de Perforación 1",
    smallWindTurbine: "Turbina Eólica Pequeña",
    tallPlatform: "Plataforma Alta",
    tallStorage: "Almacenamiento Alto",
    drillStrength1: "Fuerza de Perforación 1",
    exoRequestPlatform: "Plataforma de Pedido Exo",
    largeWindTurbine: "Turbina Eólica Grande",
    largePlatformC: "Gran Plataforma C",
    largeCurvedPlatform: "Gran Plataforma Curva",
    largeStorage: "Almacenamiento Grande",
    xlWindTurbine: "Turbina Eólica XL",
    extraLargePlatformA: "Plataforma Extra Grande A",
    extraLargeCurvedPlatform: "Plataforma Extra Grande Curva",
    extraLargeStorage: "Almacenamiento Extra Grande",
    mediumShuttle: "Nave Mediana",
    largeShuttle: "Nave Grande",
    worklight: "Luz de Trabajo",
    smallSolarPanel: "Panel Solar Pequeño",
    extenders: "Extensores",
    mediumSolarPanel: "Panel Solar Mediano",
    powerSensor: "Sensor de Energía",
    solarArray: "Matriz Solar",
    oxygenTank: "Tanque de Oxígeno",

    mediumResourceCanister: "Contenedor de Recursos Mediano",
    mediumFluidSoilCanister: "Contenedor de Fluido y Suelo Mediano",
    mediumGasCanister: "Contenedor de Gas Mediano",
    largeResourceCaniester: "Contenedor de Recursos Grande",
    largeSolarPanel: "Panel Solar Grande",
    mediumShredder: "Destructor Mediano",
    largeShredder: "Destructor Grande",
    extraLargePlatformB: "Plataforma Extra Grande B",
    extraLargePlatformC: "Plataforma Extra Grande C",
    figurinePlatform: "Plataforma de Figuritas",
    crane: "Grúa",
    largeResourceCanister: "Contenedor de Recursos Grande",
    mediumStorageSilo: "Silo de Almacenamiento Mediano",
    floodlight: "Foco de Luz",
    powerCells: "Celdas de Energía",
    wideMod: "Modificación Ancha",
    alignmentMod: "Modificación de Alineación",
    inhibitorMod: "Modificación Inhibidora",
    boostMod: "Modificación de Impulso",
    narrowMod: "Modificación Estrecha",
    terrainAnalyzer: "Analizador de Terreno",
    smallBattery: "Batería Pequeña",
    batterySensor: "Sensor de Batería",
    buttonRepeater: "Repetidor de Botón",
    proximityRepeater: "Repetidor de Proximidad",
    delayRepeater: "Repetidor de Retraso",
    countRepeater: "Repetidor de Cuenta",
    recreationalSphere: "Esfera Recreativa",
    largeRover: "Rover Grande",
    paver: "Pavimentadora",
    drillMod3: "Modificación de Perforación 3",

    drillStrength3: "Potencia de Perforación 3",
    fireworks: "Fuegos Artificiales",
    fieldShelter: "Refugio de Campo",
    portableOxygenator: "Oxigenador Portátil",
    holographicFigurine: "Figurita Holográfica",
    mediumRover: "Rover Mediano",
    shelter: "Refugio",
    winch: "Malacate",
    autoExtractor: "Auto Extractor",
    probeScanner: "Escáner de Sondas",
    hydrazineThruster: "Propulsor de Hidracina",
    largeStorageSiloA: "Gran Silo de Almacenamiento A",
    largeStorageSiloB: "Gran Silo de Almacenamiento B",
    extraLargeShredder: "Trituradora Extra Grande",
    drillStrength2: "Potencia de Perforación 2",
    hydrazineJetPack: "Jet Pack de Hidracina",
    drillMod2: "Modificación de Perforación 2",
    mediumTPlatform: "Plataforma T Mediana",
    mediumBuggyHorn: "Cuerno de Buggy Mediano",
    smallCanister: "Lata Pequeña",
    powerSwitch: "Interruptor de Energía",
    automoton001: "Automotón 001",
    automoton002: "Automotón 002",
    cubicObject: "Objeto Cúbico",
    stellarObject: "Objeto Estelar",
    cosmigBauble: "Bolita Cósmica",
    scrap: "Chatarra",
    event: "Evento",
    full: "Completo",

    levelingBlock: "Bloque de Nivelación",
    unlocked: "Desbloqueado",
    smallCamera: "Cámara Pequeña",
    smallTrumpetHorn: "Trompeta Pequeña",
    hoverboard: "Hoverboard",
    largeExtendedPlatform: "Plataforma Grande Extendida",
    largeActiveStorage: "Gran Almacenamiento Activo",
    largeFogHorn: "Gran Cuerno de Niebla",
    vtol: "VTOL",
    sourceVtol: "Despegue y Aterrizaje Vertical (VTOL)",
    printTitle: "Imprimir los Elementos",
    xlExtendedPlatform: "Plataforma XL Extendida",
    sourcePortableSmeltingFurnace: "Horno de Fundición Portátil",
    gravityGlobe: "Globo de Gravedad",
    easy: "Fácil",
    planetDetails: "Detalles del Planeta",
    size: "Tamaño",
    medium: "Medio",
    difficulty: "Dificultad",
    dayNigthCycle: "Ciclo Día/Noche",
    minutes: "Minutos",
    sunPower: "Energía Solar",
    windPower: "Energía Eólica",
    location: "Ubicación: ",
    caveLayer: "Capa de Cueva",
    mantleLayer: "Capa de Manto",
    small: "Pequeño",
    grayPlains: "Llanuras Grises",
    veryHigh: "Muy Alto",
    low: "Bajo",
    high: "Alto",
    veryLow: "Muy Bajo",
    purpleHills: "Colinas Moradas",
    mountains: "Montañas",
    icePlains: "Llanuras de Hielo",
    hard: "Difícil",
    veryHard: "Muy Difícil",

    // Long Names
    backpackPrinter: "Impresora de Mochila",
    smallPrinter: "Impresora Pequeña",
    mediumPrinter: "Impresora Mediana",
    largePrinter: "Impresora Grande",
    soilCentrifuge: "Centrífuga de Suelo",
    chemistryLab: "Laboratorio de Química",
    atmosphericCondenser: "Condensador Atmosférico",
    tradePlatform: "Plataforma de Comercio",
    smeltingFurnace: "Horno de Fundición",

    // Printers table
    craftedAt: "Elaborado En",
    recipe: "Receta",
    unlockCost: "Costo de Desbloqueo",
    powerConsumption: "Consumo de Energía",
    "-": "-"
}