export default {
    //App commun texts
    welcome: "LA MANERA MÁS FÁCIL\nDE USAR\nLA ASTROPEDIA",
    userIdentification: "¿Cuál es tu\nnombre de Astroneer?",
    language: "Idioma: ",
    whatYouWant: "¿No ves lo que quieres?",
    contactUs: "Contáctanos",
    contactUsDefaultName: "Jugador de Astroneer",
    contactUsMail: "noreply",
    contactUsMessageFrom: "\n\n\nMensaje de: ",
    contactUsMessageReply: "\nResponder a: ",
    contactUsWarning: "¡Necesitas incluir un mensaje!",
    contactUsPlaceholderEmail: "Correo electrónico",
    contactUsPlaceholderName: "Nombre",
    contactUsPlaceholderMessage: "Mensaje",
    avatar: "Avatar: ",
    name: "Nombre: ",
    aboutUs: "Sobre Nosotros",
    aboutUsCredit: "Créditos",
    aboutUsDeveloped: "Desarrollado por MIDDLEWARE DEV",
    aboutUsDesign: "Diseño",
    aboutUsThanks: "Con Agradecimientos Especiales a",
    aboutUsTranslation: "Traducciones",
    warningTitle: "Advertencia",
    warningMessage: "Los cambios solo se aplicarán después de que reinicies la Astropedia",
    warningButton: "Aceptar",

    //Titles
    mainTitle: "Astropedia",
    planetsTitle: "Planetas",
    resourcesTitle: "Recursos",
    favoritesTitle: "Favoritos",
    naturalResourcesTitle: "Recursos Naturales",
    atmosphericResourcesTitle: "Recursos Atmosféricos",
    sourceTitle: "Fuente",
    usesTitle: "Usos",
    printers: "Impresoras",
    settings: "Configuración",

    //Planet's names
    sylva: "Sylva",
    desolo: "Desolo",
    calidor: "Calidor",
    vesania: "Vesania",
    novus: "Novus",
    glacio: "Glacio",
    atrox: "Atrox",

    //Basic Resource's names
    ammonium: "Amonio",
    astronium: "Astronio",
    clay: "Arcilla",
    compound: "Compuesto",
    graphite: "Grafito",
    hematite: "Hematita",
    laterite: "Laterita",
    lithium: "Litio",
    malachite: "Malaquita",
    organic: "Orgánico",
    quartz: "Cuarzo",
    resin: "Resina",
    sphalerite: "Esfalerita",
    titanite: "Titanita",
    wolframite: "Wolframita",
    aluminum: "Aluminio",
    carbon: "Carbono",
    ceramic: "Cerámica",
    copper: "Cobre",
    glass: "Vidrio",
    iron: "Hierro",
    titanium: "Titanio",
    tungsten: "Tungsteno",
    zinc: "Zinc",

    //Gas names
    argon: "Argón",
    helium: "Helio",
    hydrogen: "Hidrógeno",
    methane: "Metano",
    nitrogen: "Nitrógeno",
    sulfur: "Azufre",

    //Compost Resourse name
    aluminumAlloy: "Aleación de Aluminio",
    diamond: "Diamante",
    explosivePowder: "Polvo Explosivo",
    hydrazine: "Hidracina",
    graphene: "Grafeno",
    nanocarbonAlloy: "Aleación de Nanocarbono",
    plastic: "Plástico",
    rubber: "Caucho",
    silicone: "Silicona",
    steel: "Acero",
    titaniumAlloy: "Aleación de Titanio",
    tungstenCarbide: "Carburo de Tungsteno",

    //Sources and Items name
    sourceAllPlanets: "Todos los Planetas",
    solidFuelThruster: "Propulsor de Combustible Sólido",
    exoChip: "Exo Chip",
    packager: "Empaquetador",
    solidFuelJumpJet: "Propulsor de Combustible Sólido",
    dynamite: "Dinamita",
    smallGenerator: "Generador Pequeño",
    tether: "Anclaje",
    roverSeat: "Asiento de Rover",
    trailer: "Remolque",
    researchChamber: "Cámara de Investigación",
    largeRoverSeat: "Asiento Grande de Rover",
    buggy: "Buggy",
    splitter: "Divisor",
    autoArm: "Brazo Automático",
    mediumBattery: "Batería Mediana",
    rtg: "RTG",
    glowsticks: "Bastones Luminosos",
    beacon: "Baliza",

    storageSensor: "Sensor de Almacenamiento",
    mediumSensorArch: "Arco de Sensor Mediano",
    largeSensorRing: "Anillo de Sensor Grande",
    largeSensorHoopA: "Aro de Sensor Grande A",
    largeSensorHoopB: "Aro de Sensor Grande B",
    xlSensorArch: "Arco de Sensor XL",
    xlSensorCanopy: "Toldo de Sensor XL",
    xlSensorHoopA: "Aro de Sensor XL A",
    xlSensorHoopB: "Aro de Sensor XL B",
    canister: "Contenedor",
    oxygenFilter: "Filtro de Oxígeno",
    mediumStorage: "Almacenamiento Mediano",
    mediumPlatformA: "Plataforma Mediana A",
    mediumPlatformB: "Plataforma Mediana B",
    mediumPlatformC: "Plataforma Mediana C",
    largePlatformA: "Plataforma Grande A",
    largePlatformB: "Plataforma Grande B",
    oxygenator: "Oxigenador",
    mediumGenerator: "Generador Mediano",
    mediumWindTurbine: "Turbina Eólica Mediana",
    tractor: "Tractor",

    largeTPlatform: "Gran Plataforma T",
    smallShuttle: "Nave Pequeña",
    landingPad: "Plataforma de Aterrizaje",
    drillMod1: "Modificación de Perforación 1",
    smallWindTurbine: "Turbina Eólica Pequeña",
    tallPlatform: "Plataforma Alta",
    tallStorage: "Almacenamiento Alto",
    drillStrength1: "Fuerza de Perforación 1",
    exoRequestPlatform: "Plataforma de Pedido Exo",
    largeWindTurbine: "Turbina Eólica Grande",
    largePlatformC: "Gran Plataforma C",
    largeCurvedPlatform: "Gran Plataforma Curva",
    largeStorage: "Almacenamiento Grande",
    xlWindTurbine: "Turbina Eólica XL",
    extraLargePlatformA: "Plataforma Extra Grande A",
    extraLargeCurvedPlatform: "Plataforma Extra Grande Curva",
    extraLargeStorage: "Almacenamiento Extra Grande",
    mediumShuttle: "Nave Mediana",
    largeShuttle: "Nave Grande",
    worklight: "Luz de Trabajo",
    smallSolarPanel: "Panel Solar Pequeño",
    extenders: "Extensores",
    mediumSolarPanel: "Panel Solar Mediano",
    powerSensor: "Sensor de Energía",
    solarArray: "Matriz Solar",
    oxygenTank: "Tanque de Oxígeno",

    mediumResourceCanister: "Contenedor de Recursos Mediano",
    mediumFluidSoilCanister: "Contenedor de Fluido y Suelo Mediano",
    mediumGasCanister: "Contenedor de Gas Mediano",
    largeResourceCaniester: "Contenedor de Recursos Grande",
    largeSolarPanel: "Panel Solar Grande",
    mediumShredder: "Destructor Mediano",
    largeShredder: "Destructor Grande",
    extraLargePlatformB: "Plataforma Extra Grande B",
    extraLargePlatformC: "Plataforma Extra Grande C",
    figurinePlatform: "Plataforma de Figuritas",
    crane: "Grúa",
    largeResourceCanister: "Contenedor de Recursos Grande",
    mediumStorageSilo: "Silo de Almacenamiento Mediano",
    floodlight: "Foco de Luz",
    powerCells: "Celdas de Energía",
    wideMod: "Modificación Ancha",
    alignmentMod: "Modificación de Alineación",
    inhibitorMod: "Modificación Inhibidora",
    boostMod: "Modificación de Impulso",
    narrowMod: "Modificación Estrecha",
    terrainAnalyzer: "Analizador de Terreno",
    smallBattery: "Batería Pequeña",
    batterySensor: "Sensor de Batería",
    buttonRepeater: "Repetidor de Botón",
    proximityRepeater: "Repetidor de Proximidad",
    delayRepeater: "Repetidor de Retraso",
    countRepeater: "Repetidor de Cuenta",
    recreationalSphere: "Esfera Recreativa",
    largeRover: "Rover Grande",
    paver: "Pavimentadora",
    drillMod3: "Modificación de Perforación 3",

    drillStrength3: "Potencia de Perforación 3",
    fireworks: "Fuegos Artificiales",
    fieldShelter: "Refugio de Campo",
    portableOxygenator: "Oxigenador Portátil",
    holographicFigurine: "Figurita Holográfica",
    mediumRover: "Rover Mediano",
    shelter: "Refugio",
    winch: "Malacate",
    autoExtractor: "Auto Extractor",
    probeScanner: "Escáner de Sondas",
    hydrazineThruster: "Propulsor de Hidracina",
    largeStorageSiloA: "Gran Silo de Almacenamiento A",
    largeStorageSiloB: "Gran Silo de Almacenamiento B",
    extraLargeShredder: "Trituradora Extra Grande",
    drillStrength2: "Potencia de Perforación 2",
    hydrazineJetPack: "Jet Pack de Hidracina",
    drillMod2: "Modificación de Perforación 2",
    mediumTPlatform: "Plataforma T Mediana",
    mediumBuggyHorn: "Cuerno de Buggy Mediano",
    smallCanister: "Lata Pequeña",
    powerSwitch: "Interruptor de Energía",
    automoton001: "Automotón 001",
    automoton002: "Automotón 002",
    cubicObject: "Objeto Cúbico",
    stellarObject: "Objeto Estelar",
    cosmigBauble: "Bolita Cósmica",
    scrap: "Chatarra",
    event: "Evento",
    full: "Completo",

    levelingBlock: "Bloque de Nivelación",
    unlocked: "Desbloqueado",
    smallCamera: "Cámara Pequeña",
    smallTrumpetHorn: "Trompeta Pequeña",
    hoverboard: "Hoverboard",
    largeExtendedPlatform: "Plataforma Grande Extendida",
    largeActiveStorage: "Gran Almacenamiento Activo",
    largeFogHorn: "Gran Cuerno de Niebla",
    vtol: "VTOL",
    sourceVtol: "Despegue y Aterrizaje Vertical (VTOL)",
    printTitle: "Imprimir los Elementos",
    xlExtendedPlatform: "Plataforma XL Extendida",
    sourcePortableSmeltingFurnace: "Horno de Fundición Portátil",
    gravityGlobe: "Globo de Gravedad",
    easy: "Fácil",
    planetDetails: "Detalles del Planeta",
    size: "Tamaño",
    medium: "Medio",
    difficulty: "Dificultad",
    dayNigthCycle: "Ciclo Día/Noche",
    minutes: "Minutos",
    sunPower: "Energía Solar",
    windPower: "Energía Eólica",
    location: "Ubicación: ",
    caveLayer: "Capa de Cueva",
    mantleLayer: "Capa de Manto",
    small: "Pequeño",
    grayPlains: "Llanuras Grises",
    veryHigh: "Muy Alto",
    low: "Bajo",
    high: "Alto",
    veryLow: "Muy Bajo",
    purpleHills: "Colinas Moradas",
    mountains: "Montañas",
    icePlains: "Llanuras de Hielo",
    hard: "Difícil",
    veryHard: "Muy Difícil",

    // Long Names
    backpackPrinter: "Impresora de Mochila",
    smallPrinter: "Impresora Pequeña",
    mediumPrinter: "Impresora Mediana",
    largePrinter: "Impresora Grande",
    soilCentrifuge: "Centrífuga de Suelo",
    chemistryLab: "Laboratorio de Química",
    atmosphericCondenser: "Condensador Atmosférico",
    tradePlatform: "Plataforma de Comercio",
    smeltingFurnace: "Horno de Fundición",

    // Printers table
    craftedAt: "Elaborado En",
    recipe: "Receta",
    unlockCost: "Costo de Desbloqueo",
    powerConsumption: "Consumo de Energía",
    "-": "-",

    railway: "Vía férrea",
    missionReward: "Recompensa de misión",

    railEngine: "Motor de ferrocarril",
    details: "Detalles",
    railEngineUseLine1: "Los motores de ferrocarril se utilizan para transportar objetos y recursos usando vagones de ferrocarril. Se detienen en cualquier estación de ferrocarril que esté configurada para detener motores de ferrocarril manuales o automatizados.",
    railEngineUseLine2: "Los motores de ferrocarril pueden activarse para comenzar a moverse mediante elementos de automatización, como el repetidor de proximidad y el repetidor de botón. Los motores de ferrocarril y los vagones se moverán en la dirección en la que viajaron por última vez, a menos que se encuentren en un callejón sin salida, en cuyo caso se moverán en la dirección opuesta.",
    railEngineUseLine3: "2 motores de ferrocarril en la parte delantera y trasera lo harán ir más rápido (funciona con C.O.L.E)",
    railEngineDescriptionLine1: "Los motores de ferrocarril son un artículo ferroviario en Astroneer. Permiten a los jugadores viajar por los rieles, tienen dos ranuras pequeñas y proporcionan oxígeno al jugador. Conectar a vagones de ferrocarril aumentará la velocidad del vagón. Conectar más de 1 motor de ferrocarril a un vagón no aumentará la velocidad del tren.",

    railCar: "Vagón de ferrocarril",
    railCarDescriptionLine1: "Los vagones de ferrocarril son un artículo ferroviario en Astroneer. Permiten transportar objetos y recursos a lo largo de las líneas ferroviarias, con una ranura grande y pueden formar un tren con vagones de ferrocarril, motores de ferrocarril o C.O.L.E.s.",
    railCarUseLine1: "Los vagones de ferrocarril se usan para transportar objetos y recursos a lo largo de las líneas ferroviarias y hacia estaciones de ferrocarril conectadas. Los vagones de ferrocarril pueden formar un tren (con hasta 6 partes) colocándolos en un riel y luego acoplando vagones adicionales, o un motor de ferrocarril o C.O.L.E.. Los vagones de ferrocarril pueden moverse por sí mismos, pero un motor los hará moverse más rápido.",

    railStation: "Estación de ferrocarril",
    railStationDescriptionLine1: "Las estaciones de ferrocarril son un artículo ferroviario en Astroneer. Permiten a los vagones de ferrocarril detenerse, cargar o descargar su carga, así como llamar a los vehículos ferroviarios a la estación.",
    railStationUseLine1: "Las estaciones de ferrocarril se usan principalmente como paradas para vagones y motores de ferrocarril, lo que permite la carga y descarga de objetos y recursos. El panel de control en la plataforma de la estación permite al jugador cambiar los modos de parada y carga y puede llamar a vehículos ferroviarios.",
    railStationUseLine2: "El modo de parada permite que la estación no detenga vehículos ferroviarios, detenga solo los vehículos no llamados (aquellos automatizados desde otros lugares o pilotados por el jugador), o que detenga todos los vehículos ferroviarios.",
    railStationUseLine3: "El modo de carga permite que la estación cargue objetos en los almacenamientos de los vagones de ferrocarril o descargue objetos en los almacenamientos en la plataforma de la estación. Cuando están en modo de carga, los vagones de ferrocarril que se detienen en una estación tendrán todas las ranuras llenas en el almacenamiento del vagón. Al llegar a una estación de descarga, todos los almacenamientos se vaciarán de los vagones de ferrocarril, si hay suficiente espacio disponible.",
    railStationUseLine4: "Las estaciones de ferrocarril tienen dos pines de destino y dos ranuras para pines, lo que permite una automatización más controlada. Los pines de destino enviarán una señal a cualquier elemento conectado cuando un vehículo ferroviario pase o se detenga en la estación. Cuando se envía una señal a las ranuras para pines, la estación enviará vehículos ferroviarios por el lado de la estación de la ranura que fue activada.",
    railStationUseLine5: "Colocar un pin de destino de sensores o repetidores directamente en la estación llamará a vehículos ferroviarios a ella.",
    railStationUseLine6: "Las estaciones de ferrocarril tienen una ranura junto al panel de control destinada a colocar un baliza.",

    railPost: "Poste de ferrocarril",
    railPostDescriptionLine1: "El poste de ferrocarril es un artículo ferroviario en Astroneer. Permite la creación de líneas ferroviarias y puede usarse para recordar motores de ferrocarril. También puede usarse como un 'extensor extendido', siendo capaz de canalizar energía y oxígeno entre bases. Tiene 2 ranuras pequeñas que pueden ser útiles para colocar una luz de trabajo con sensor de energía.",
    railPostUseLine1: "Los postes de ferrocarril se colocan desde un paquete de postes de ferrocarril.",
    railPostUseLine2: "Colocar un poste de ferrocarril dentro del alcance de otro conectará una línea ferroviaria entre ellos, deformando cualquier terreno que pueda estar en el camino.",
    railPostUseLine3: "Los postes de ferrocarril pueden colocarse en cualquier terreno, permitiendo su colocación en paredes y techos de cuevas.",
    railPostUseLine4: "La distancia máxima de colocación para el poste se muestra como un dial de color en la base del poste al colocarlo.",
    railPostUseLine5: " - Blanco indica una colocación válida, por debajo de la longitud máxima del riel.",
    railPostUseLine6: " - Azul indica una colocación válida en la longitud óptima del riel.",
    railPostUseLine7: " -  Rosa indica una colocación no válida, ya sea por estar demasiado lejos, demasiado cerca o por crear una curva demasiado cerrada.",

    railPostBundle: "Paquete de postes de ferrocarril",
    railPostBundleDescriptionLine1: "Los paquetes de postes de ferrocarril son un artículo ferroviario en Astroneer. Son un paquete de 10 postes de ferrocarril y se pueden colocar en las ranuras auxiliares de la mochila para facilitar la colocación de postes de ferrocarril.",
    railPostBundleUseLine1: "Los paquetes de postes de ferrocarril se usan para colocar postes de ferrocarril en el terreno para expandir las líneas ferroviarias. Los paquetes pueden colocarse en las ranuras auxiliares de la mochila, lo que permite una colocación más rápida presionando las teclas de contexto (PC: C o V).",

    tallRailPost: "Poste de ferrocarril alto",
    tallRailPostDescriptionLine1: "Los postes de ferrocarril altos son un artículo ferroviario en Astroneer. Permiten la creación de líneas ferroviarias y pueden usarse para recordar motores de ferrocarril. Son una versión alta de los postes de ferrocarril, permitiendo secciones más altas de rieles.",
    tallRailPostUseLine1: "Los postes de ferrocarril altos se colocan desde un paquete de postes de ferrocarril altos.",
    tallRailPostUseLine2: "Colocar un poste de ferrocarril alto dentro del alcance de otro conectará una línea ferroviaria entre ellos, deformando cualquier terreno que pueda estar en el camino.",
    tallRailPostUseLine3: "Los postes de ferrocarril altos pueden colocarse en cualquier terreno, permitiendo su colocación en paredes y techos de cuevas.",
    tallRailPostUseLine4: "La distancia máxima de colocación para el poste se muestra como un dial de color en la base del poste al colocarlo.",
    tallRailPostUseLine5: " - Blanco indica una colocación válida, por debajo de la longitud máxima del riel.",
    tallRailPostUseLine6: " - Azul indica una colocación válida en la longitud óptima del riel.",
    tallRailPostUseLine7: " - Rosa indica una colocación no válida, ya sea por estar demasiado lejos, demasiado cerca o por crear una curva demasiado cerrada.",

    tallRailPostBundle: "Paquete de postes de ferrocarril alto",
    tallRailPostBundleDescriptionLine1: "Los paquetes de postes de ferrocarril alto son un artículo ferroviario en Astroneer. Son un paquete de 10 postes de ferrocarril alto.",
    tallRailPostBundleUseLine1: "Los paquetes de postes de ferrocarril alto se usan para colocar postes de ferrocarril alto en el terreno para expandir las líneas ferroviarias. Los paquetes pueden colocarse en las ranuras auxiliares de la mochila, lo que permite una colocación más rápida presionando las teclas de contexto (PC: C o V).",

    railJunctions: "Cruces de ferrocarril",
    railJunctionDescriptionLine1: "Los cruces de ferrocarril son un elemento ferroviario en Astroneer. Permiten la creación de cruces en las líneas ferroviarias que dividen las líneas en tres direcciones. Cada paquete contiene 5 cruces de ferrocarril y pueden colocarse en las ranuras auxiliares de la mochila para una fácil colocación de postes.",
    railJunctionUseLine1: "Los paquetes de cruces de ferrocarril se utilizan para colocar cruces de ferrocarril en el terreno para expandir las líneas ferroviarias y cambiar la dirección de los trenes que circulan por la línea. Los paquetes pueden colocarse en las ranuras auxiliares de la mochila, lo que permite una colocación más rápida presionando las teclas de contexto (PC: C o V).",
    railJunctionUseLine2: " Interactuar con el cruce de ferrocarril cambiará la conexión ferroviaria entre los tres estados posibles. Cuando viajas por la línea de ferrocarril usando un Motor Ferroviario, Izquierda y Derecha (PC: A y D) pueden usarse para cambiar la dirección del cruce, cuando el tren está lo suficientemente cerca del cruce.",
    railJunctionUseLine3: "Los cruces de ferrocarril tienen tres ranuras de entrada para señales de automatización, ubicadas entre cada una de las tres direcciones del riel. Enviar una señal a una entrada de automatización conectará el riel a cada lado de esa señal de entrada. Las señales también se pueden enviar en cualquier parte del cruce en sí, lo que solo hará que el cruce recorra las conexiones, similar a la interacción manual con el cruce.",
    railJunctionUseLine4: "Colocar un cruce de ferrocarril dentro del alcance de otro poste o cruce de ferrocarril conectará una línea de ferrocarril entre ellos, deformando cualquier terreno que pueda estar en el camino.",
    railJunctionUseLine5: "Los cruces de ferrocarril pueden colocarse en cualquier terreno, lo que permite su colocación en paredes y techos de cuevas.",
    railJunctionUseLine6: "La distancia máxima de colocación para el cruce se muestra como un dial de color en la base del cruce al colocarlo.",
    railJunctionUseLine7: " - El blanco indica una colocación válida, por debajo de la longitud máxima del riel",
    railJunctionUseLine8: " - El azul indica una colocación válida en la longitud óptima del riel",
    railJunctionUseLine9: " - El rosa indica una colocación inválida, ya sea por estar demasiado lejos, demasiado cerca o por crear un giro demasiado cerrado.",

    railJunctionsBundle: "Paquete de cruces de ferrocarril",
    railJunctionBundleDescriptionLine1: "Los paquetes de cruces de ferrocarril son un elemento ferroviario en Astroneer. Son un paquete de 5 cruces de ferrocarril, y pueden colocarse en las ranuras auxiliares de la mochila para una fácil colocación de postes.",
    railJunctionBundleUseLine1: "Los paquetes de cruces de ferrocarril se utilizan para colocar cruces de ferrocarril en el terreno para expandir las líneas ferroviarias. Los paquetes pueden colocarse en las ranuras auxiliares de la mochila, lo que permite una colocación más rápida presionando las teclas de contexto (PC: C o V).",

    cole: "C.O.L.E",
    coleDescriptionLine1: "C.O.L.E. (Computer Operated Logistics Engines), son un elemento ferroviario en Astroneer. Permiten viajar a lo largo de los rieles, tienen dos ranuras pequeñas y proporcionan oxígeno al jugador. Son más rápidos que un Motor de Ferrocarril y no son dañinos.",
    coleUseLine1: "Recompensado al completar la misión Compañero de Viaje.",
    coleUseLine2: "La parte delantera de C.O.L.E. tiene una cara animada que cambia dependiendo de si está vacío, un jugador está sentado en él o si se está moviendo con el jugador sentado en él.",
    coleUseLine3: " - Cada partida solo puede tener un C.O.L.E por jugador",
    coleUseLine4: " - C.O.L.E. no se puede fabricar",
    coleUseLine5: " - C.O.L.E. no se puede colocar en almacenamiento a menos que esté empaquetado.",

    sitePylon: "Pilar de sitio",
    sitePylonDescriptionLine1: "Los pilares de sitio son un elemento ferroviario en Astroneer. Permiten la creación de líneas ferroviarias y pueden usarse para llamar a los Motores de Ferrocarril al pilar de sitio. Aparecen en Glacio y Calidor cerca de objetos de misión.",
    sitePylonUseLine1: "Los pilares de sitio aparecen en Glacio y Calidor cerca de objetos de misión, como Módulos de carga, Argón congelado, Artefactos y Obeliscos.",
    sitePylonUseLine2: "Los pilares de sitio conectarán las líneas ferroviarias con cualquier otro pilar, poste de ferrocarril, poste de ferrocarril alto o cruce de ferrocarril. Se utilizan mejor con los cruces, ya que los pilares de sitio son un callejón sin salida.",
    sitePylonUseLine3: "Los pilares de sitio pueden ser recogidos y movidos para una mejor colocación de los rieles. El Empaquetador se puede usar en él para un mejor transporte.",
    
}