export default {
        //App commun texts
        welcome: "ŁATWIEJSZY SPOSÓB\nNA KORZYSTANIE\nZ ASTROPEDII",
        userIdentification: "Jakie jest twoje\nimię w grze Astroneer?",
        language: "Język: ",
        whatYouWant: "Nie widzisz, czego szukasz?",
        contactUs: "Skontaktuj się z nami",
        contactUsDefaultName: "Gracz Astroneer",
        contactUsMail: "noreply",
        contactUsMessageFrom: "\n\n\nWiadomość od: ",
        contactUsMessageReply: "\nOdpowiedz na: ",
        contactUsWarning: "Musisz dołączyć wiadomość!",
        contactUsPlaceholderEmail: "Email",
        contactUsPlaceholderName: "Imię",
        contactUsPlaceholderMessage: "Wiadomość",
        avatar: "Avatar: ",
        name: "Imię: ",
        aboutUs: "O Nas",
        aboutUsCredit: "Podziękowania",
        aboutUsDeveloped: "Opracowane przez MIDDLEWARE DEV",
        aboutUsDesign: "Projekt",
        aboutUsThanks: "Specjalne Podziękowania dla",
        aboutUsTranslation: "Tłumaczenia",
        warningTitle: "Ostrzeżenie",
        warningMessage: "Zmiany będą obowiązywać dopiero po ponownym uruchomieniu Astropedii",
        warningButton: "Ok",

        //Titles
        mainTitle: "Astropedia",
        planetsTitle: "Planety",
        resourcesTitle: "Zasoby",
        favoritesTitle: "Ulubione",
        naturalResourcesTitle: "Zasoby Naturalne",
        atmosphericResourcesTitle: "Zasoby Atmosferyczne",
        sourceTitle: "Źródło",
        usesTitle: "Zastosowania",
        printers: "Drukarki",
        settings: "Ustawienia",

        //Planet's names
        sylva: "Sylva",
        desolo: "Desolo",
        calidor: "Calidor",
        vesania: "Vesania",
        novus: "Novus",
        glacio: "Glacio",
        atrox: "Atrox",

        //Basic Resource's names
        ammonium: "Amoniak",
        astronium: "Astronium",
        clay: "Glina",
        compound: "Związek",
        graphite: "Grafit",
        hematite: "Hematyt",
        laterite: "Lateryt",
        lithium: "Lit",
        malachite: "Malachit",
        organic: "Organiczny",
        quartz: "Kwarc",
        resin: "Żywica",
        sphalerite: "Sfaleryt",
        titanite: "Tytanit",
        wolframite: "Wolframit",
        aluminum: "Aluminium",
        carbon: "Węgiel",
        ceramic: "Ceramika",
        copper: "Miedź",
        glass: "Szkło",
        iron: "Żelazo",
        titanium: "Tytan",
        tungsten: "Wolfram",
        zinc: "Cynk",

        //Gas names
        argon: "Argon",
        helium: "Hel",
        hydrogen: "Wodór",
        methane: "Metan",
        nitrogen: "Azot",
        sulfur: "Siarka",

        //Compost Resourse name
        aluminumAlloy: "Stop aluminium",
        diamond: "Diament",
        explosivePowder: "Proch wybuchowy",
        hydrazine: "Hydrazyna",
        graphene: "Grafen",
        nanocarbonAlloy: "Stop nanowęglowy",
        plastic: "Plastik",
        rubber: "Guma",
        silicone: "Silikon",
        steel: "Stal",
        titaniumAlloy: "Stop tytanu",
        tungstenCarbide: "Węglik wolframu",

        //Sources and Items name
        sourceAllPlanets: "Wszystkie Planety",
        solidFuelThruster: "Silnik na Stałe Paliwo",
        exoChip: "Chip Exo",
        packager: "Pakowarka",
        solidFuelJumpJet: "Silnik Skokowy na Stałe Paliwo",
        dynamite: "Dynamit",
        smallGenerator: "Mały Generator",
        tether: "Przewód",
        roverSeat: "Siedzenie Łazika",
        trailer: "Przyczepa",
        researchChamber: "Komora Badawcza",
        largeRoverSeat: "Duże Siedzenie Łazika",
        buggy: "Buggy",
        splitter: "Rozdzielacz",
        autoArm: "Automatyczne Ramię",
        mediumBattery: "Średnia Bateria",
        rtg: "RTG",
        glowsticks: "Świetliki",
        beacon: "Sygnał",

        storageSensor: "Czujnik Magazynowy",
        mediumSensorArch: "Średni Czujnikowy Łuk",
        largeSensorRing: "Duży Czujnikowy Pierścień",
        largeSensorHoopA: "Duża Czujnikowa Obręcz A",
        largeSensorHoopB: "Duża Czujnikowa Obręcz B",
        xlSensorArch: "XL Czujnikowy Łuk",
        xlSensorCanopy: "XL Czujnikowy Baldachim",
        xlSensorHoopA: "XL Czujnikowa Obręcz A",
        xlSensorHoopB: "XL Czujnikowa Obręcz B",
        canister: "Kanister",
        oxygenFilter: "Filtr Tlenowy",
        mediumStorage: "Średni Magazyn",
        mediumPlatformA: "Średnia Platforma A",
        mediumPlatformB: "Średnia Platforma B",
        mediumPlatformC: "Średnia Platforma C",
        largePlatformA: "Duża Platforma A",
        largePlatformB: "Duża Platforma B",
        oxygenator: "Tlenownik",
        mediumGenerator: "Średni Generator",
        mediumWindTurbine: "Średnia Turbina Wiatrowa",
        tractor: "Traktor",

        largeTPlatform: "Duża Platforma T",
        smallShuttle: "Mały Prom",
        landingPad: "Platforma Lądowania",
        drillMod1: "Moduł Wiertniczy 1",
        smallWindTurbine: "Mała Turbina Wiatrowa",
        tallPlatform: "Wysoka Platforma",
        tallStorage: "Wysokie Magazynowanie",
        drillStrength1: "Siła Wiercenia 1",
        exoRequestPlatform: "Platforma Żądań Exo",
        largeWindTurbine: "Duża Turbina Wiatrowa",
        largePlatformC: "Duża Platforma C",
        largeCurvedPlatform: "Duża Krzywa Platforma",
        largeStorage: "Duże Magazynowanie",
        xlWindTurbine: "XL Turbina Wiatrowa",
        extraLargePlatformA: "Bardzo Duża Platforma A",
        extraLargeCurvedPlatform: "Bardzo Duża Krzywa Platforma",
        extraLargeStorage: "Bardzo Duże Magazynowanie",
        mediumShuttle: "Średni Prom",
        largeShuttle: "Duży Prom",
        worklight: "Światło Robocze",
        smallSolarPanel: "Mały Panel Solarney",
        extenders: "Rozszerzacze",
        mediumSolarPanel: "Średni Panel Solarney",
        powerSensor: "Czujnik Mocy",
        solarArray: "Tablica Solarna",
        oxygenTank: "Zbiornik Tlenowy",

        mediumResourceCanister: "Średni Pojemnik na Zasoby",
        mediumFluidSoilCanister: "Średni Pojemnik na Płyny i Glebę",
        mediumGasCanister: "Średni Pojemnik na Gaz",
        largeResourceCaniester: "Duży Pojemnik na Zasoby",
        largeSolarPanel: "Duży Panel Słoneczny",
        mediumShredder: "Średni Rozdrabniacz",
        largeShredder: "Duży Rozdrabniacz",
        extraLargePlatformB: "Dodatkowo Duża Platforma B",
        extraLargePlatformC: "Dodatkowo Duża Platforma C",
        figurinePlatform: "Platforma Figurkowa",
        crane: "Dźwig",
        largeResourceCanister: "Duży Pojemnik na Zasoby",
        mediumStorageSilo: "Średni Silos Magazynowy",
        floodlight: "Reflektor",
        powerCells: "Komórki Energii",
        wideMod: "Modulacja Szeroka",
        alignmentMod: "Modulacja Wyrównująca",
        inhibitorMod: "Modulacja Hamująca",
        boostMod: "Modulacja Wzmacniająca",
        narrowMod: "Modulacja Wąska",
        terrainAnalyzer: "Analizator Terenu",
        smallBattery: "Mała Bateria",
        batterySensor: "Czujnik Baterii",
        buttonRepeater: "Powtarzacz Przycisku",
        proximityRepeater: "Powtarzacz Bliskości",
        delayRepeater: "Powtarzacz Opóźnienia",
        countRepeater: "Powtarzacz Licznika",
        recreationalSphere: "Sfera Rekreacyjna",
        largeRover: "Duży Rover",
        paver: "Ubijak",
        drillMod3: "Modulacja Wiercenia 3",

        drillStrength3: "Siła Wiercenia 3",
        fireworks: "Fajerwerki",
        fieldShelter: "Schronienie Polowe",
        portableOxygenator: "Przenośny Tlenator",
        holographicFigurine: "Figurka Holograficzna",
        mediumRover: "Średni Rover",
        shelter: "Schron",
        winch: "Wyciągarka",
        autoExtractor: "Automatyczny Ekstraktor",
        probeScanner: "Skaner Sond",
        hydrazineThruster: "Śrutowentylator",
        largeStorageSiloA: "Duże Silos Magazynowe A",
        largeStorageSiloB: "Duże Silos Magazynowe B",
        extraLargeShredder: "Duży Rozdrabniacz",
        drillStrength2: "Siła Wiercenia 2",
        hydrazineJetPack: "Odrzutowiec Z Hydrazyną",
        drillMod2: "Modyfikacja Wiercenia 2",
        mediumTPlatform: "Średnia Platforma T",
        mediumBuggyHorn: "Średni Klakson Buggy",
        smallCanister: "Mały Pojemnik",
        powerSwitch: "Przełącznik Zasilania",
        automoton001: "Automaton 001",
        automoton002: "Automaton 002",
        cubicObject: "Obiekt Sześcienny",
        stellarObject: "Obiekt Gwiazdowy",
        cosmigBauble: "Kosmiczna Kula",
        scrap: "Złom",
        event: "Wydarzenie",
        full: "Pełny",

        levelingBlock: "Bloki Poziomujące",
        unlocked: "Odblokowany",
        smallCamera: "Mała Kamera",
        smallTrumpetHorn: "Mała Trąbka",
        hoverboard: "Deskorolka Latająca",
        largeExtendedPlatform: "Duża Rozszerzona Platforma",
        largeActiveStorage: "Duże Aktywne Magazyny",
        largeFogHorn: "Duża Syrena Mgły",
        vtol: "VTOL",
        sourceVtol: "Pionowy Start i Lądowanie (VTOL)",
        printTitle: "Drukuj Elementy",
        xlExtendedPlatform: "Bardzo Duża Rozszerzona Platforma",
        sourcePortableSmeltingFurnace: "Przenośny Piec Do Topienia",
        gravityGlobe: "Globus Grawitacji",
        easy: "Łatwy",
        planetDetails: "Szczegóły Planety",
        size: "Rozmiar",
        medium: "Średni",
        difficulty: "Trudność",
        dayNigthCycle: "Cykl Dzień/Noc",
        minutes: "Minuty",
        sunPower: "Energia Słoneczna",
        windPower: "Energia Wiatrowa",
        location: "Lokalizacja: ",
        caveLayer: "Warstwa Jaskiń",
        mantleLayer: "Warstwa Płaszcza",
        small: "Mały",
        grayPlains: "Szare Równiny",
        veryHigh: "Bardzo Wysoka",
        low: "Niski",
        high: "Wysoki",
        veryLow: "Bardzo Niski",
        purpleHills: "Fioletowe Wzgórza",
        mountains: "Góry",
        icePlains: "Lodowate Równiny",
        hard: "Trudny",
        veryHard: "Bardzo Trudny",

        // Long Names
        backpackPrinter: "Drukarka plecakowa",
        smallPrinter: "Mała drukarka",
        mediumPrinter: "Średnia drukarka",
        largePrinter: "Duża drukarka",
        soilCentrifuge: "Centryfuga glebowa",
        chemistryLab: "Laboratorium chemiczne",
        atmosphericCondenser: "Kondensator atmosferyczny",
        tradePlatform: "Platforma handlowa",
        smeltingFurnace: "Piece do przetapiania",

        // Printers table
        craftedAt: "Wytwarzane w",
        recipe: "Receptura",
        unlockCost: "Koszt Odblokowania",
        powerConsumption: "Zużycie Energii",
        "-": "-"
}