export default {
        //App commun texts
        welcome: 'ŁATWIEJSZY SPOSÓB\nUŻYWAĆ\nASTROPEDIA',
        userIdentification: 'Jaki jest Twój\nImię Astroneera?',
        language: 'Język: ',
        whatYouWant: 'Nie widzisz tego, czego chcesz? ',
        contactUs: 'Skontaktuj się z nami',
        contactUsDefaultName: 'Astroneer Player',
        contactUsMail: 'roreply',
        contactUsMessageFrom: '\n\n\nWiadomość od: ',
        contactUsMessageReply: '\nodpowiedzieć do: ',
        contactUsWarnning: 'Musisz dołączyć wiadomość!',
        contactUsPlaceholderEmail: 'Email',
        contactUsPlaceholderName: 'Nazwa',
        contactUsPlaceholderMessage: 'Wiadomość',
        avatar: 'Awatara: ',
        name: 'Nazwa: ',
        aboutUs: 'O nas',
        aboutUsCredit: 'Kredyty',
        aboutUsDeveloped: 'Opracowany przez MIDDLEWARE DEV',
        aboutUsDesign: 'Projekt',
        aboutUsThanks: 'Specjalne podziękowania dla',
        aboutUsTranslation: 'Tłumaczenia',
        warningTitle: 'Ostrzeżenie',
        warningMessage: 'Zmiana języka będzie skuteczna dopiero po ponownym uruchomieniu',
        warningButton: 'Ok',

        //Titles
        mainTitle: 'Astropedia',
        planetsTitle: 'Planety',
        resourcesTitle: 'Zasoby',
        favoritesTitle: 'Ulubione',
        naturalResourcesTitle: 'zasoby naturalne',
        atmosphericResourcesTitle: 'zasoby atmosferyczne',
        sourceTitle: 'Źródło',
        usesTitle: 'Zastosowania',
        printers: 'Drukarki',

        //Planet's names
        sylva: 'Sylva',
        desolo: 'Desolo',
        calidor: 'Calidor',
        vesania: 'Vesania',
        novus: 'Novus',
        glacio: 'Glacio',
        atrox: 'Atrox',

        //Resource's names
        ammonium: 'Amon',
        astronium: 'Astronium',
        clay: 'Glina',
        compound: 'Złozony',
        graphite: 'Grafit',
        hematite: 'Hematyt',
        laterite: 'Lateryt',
        lithium: 'Lit',
        malachite: 'Malachit',
        organic: 'Organiczny',
        quartz: 'Kwarc',
        resin: 'Żywica',
        sphalerite: 'sfaleryt',
        titanite: 'tytanit',
        wolframite: 'Wolframit',
        aluminum: 'Aluminium',
        carbon: 'Węgiel',
        ceramic: 'Ceramiczny',
        copper: 'Miedź',
        glass: 'Szkło',
        iron: 'Żelazo',
        titanium: 'Tytan',
        tungsten: 'Wolfram',
        zinc: 'Cynk',
        argon: 'Argon',
        helium: 'Hel',
        hydrogen: 'Wodór',
        methane: 'Metan',
        nitrogen: 'Azot',
        sulfur: 'Siarka',
        aluminumAlloy: 'Stop aluminium',
        diamond: 'Diament',
        explosivePowder: 'P. Wybuchowy',
        hydrazine: 'Hydrazyna',
        graphene: 'Grafen',
        nanocarbonAlloy: 'S. nanowęg...',
        plastic: 'Plastik',
        rubber: 'Gumowy',
        silicone: 'Silikon',
        steel: 'Stal',
        titaniumAlloy: 'Stop Tytanu',
        tungstenCarbide: 'Węg. wolframu',

        //Sources and Items name
        sourceAllPlanets: 'Wszystkie planety',
        solidFuelThruster: 'Paliwo stałe dla Silników Manewrowych',
        exoChip: 'Egzo chip',
        packager: 'Pakownik',
        solidFuelJumpJet: 'Plecak Ordzutowy na Paliwo Stałe',
        dynamite: 'Dynamit',
        smallGenerator: 'Mały generator',
        tether: 'Przewody',
        roverSeat: 'Siedzenie łazika',
        tractor: 'Ciągnik',
        researchChamber: 'Komora Badawcza',
        largeRoverSeat: 'Duże siedzenie łazika',
        buggy: 'Gazik',
        splitter: 'Rozgałęźnik',
        autoArm: 'Auto-raimę',
        mediumBattery: 'Średnia bateria',
        rtg: 'RTG',
        glowsticks: 'Słupy Świetlne',
        beacon: 'Nadajnik',
        storageSensor: 'Czujnik Schowka',
        mediumSensorArch: 'Średni Czujnika łukowy',
        largeSensorRing: 'Duży czujnika pierścieniowy',
        largeSensorHoopA: 'Duża czujnika pierścieniowy A',
        largeSensorHoopB: 'Duża czujnika pierścieniowy B',
        xlSensorArch: 'Czujnika Łukowy Xl',
        xlSensorCanopy: 'czujnika Baldachimowy Xl',
        xlSensorHoopA: 'czujnika pierścieniowy A Xl',
        xlSensorHoopB: 'czujnika pierścieniowy B Xl',
        canister: 'Mały Kanister',
        oxygenFilter: 'Filtry tlenowe',
        mediumStorage: 'Średni magazyn',
        mediumPlatformA: 'Średnia platforma A',
        mediumPlatformB: 'średnia Platforma B',
        mediumPlatformC: 'średnia Platforma C',
        largePlatformA: 'Duża platforma A',
        largePlatformB: 'Duża platforma B',
        oxygenator: 'Natleniacz',
        mediumGenerator: 'Średni generator',
        mediumWindTurbine: 'Średnia turbina wiatrowa',
        trailer: 'Przyczepa',
        largeTPlatform: 'Duża platforma w kształci T',
        smallShuttle: 'Mały Prom',
        landingPad: 'Lądowisko',
        sourceAluminumAlloy: 'Stop aluminium',
        sourceExplosivePowder: 'Proszek Wybuchowy ',
        sourceNanocarbonAlloy: 'Stop nanowęglowy',
        sourceTungstenCarbide: 'Węglik wolframu',
        drillMod1: 'Świder Mod 1',
        smallWindTurbine: 'Mała turbina wiatrowa',
        tallPlatform: 'Wysoka platforma',
        tallStorage: 'Wysokie miejsce do przechowywania',
        drillStrength1: 'Siła Świdra 1',
        exoRequestPlatform: 'Platforma Wniosków Exo',
        largeWindTurbine: 'Duża turbina wiatrowa',
        largePlatformC: 'Duża platforma C',
        largeCurvedPlatform: 'Duża zakrzywiona plansza',
        largeStorage: 'Duży Magazyn',
        xlWindTurbine: 'turbina wiatrowa Xl',
        extraLargePlatformA: 'Ekstra duża platforma A',
        extraLargeCurvedPlatform: 'Bardza duża zakrzywiona plansza',
        extraLargeStorage: 'Ekstra Duży Magazyn',
        mediumShuttle: 'Średni prom',
        largeShuttle: 'Duży prom',
        worklight: 'Światło Robocze',
        smallSolarPanel: 'Mały Słoneczny',
        extenders: 'Przedłużacze',
        mediumSolarPanel: 'Średni Słoneczny',
        powerSensor: 'Czujnik mocy',
        solarArray: 'Panele słoneczne',
        oxygenTank: 'PrzenoŚny Natleniacz',
        mediumResourceCanister: 'Średni pojemnik na zasoby',
        mediumFluidSoilCanister: 'Średni kanister na ciecz i glebę',
        mediumGasCanister: 'Średni Kanister na gaz',
        largeResourceCaniester: 'Duży pojemnik na zasoby',
        largeSolarPanel: 'Duży panel słoneczny',
        mediumShredder: 'średnia rozdrabniarka',
        largeShredder: 'Wielka Rozdrabniarka',
        extraLargePlatformB: 'Ekstra duża platforma B',
        extraLargePlatformC: 'Ekstra duża platforma C',
        figurinePlatform: 'Plansza do Figurek',
        crane: 'Dźwig',
        largeResourceCanister: 'Duży pojemnik na zasoby',
        mediumStorageSilo: 'Średni silos do przechowywania',
        floodlight: 'Reflektor',
        powerCells: 'Ogniwa Zasilające',
        boostMod: 'Mod Wzmocnienia',
        wideMod: 'mod Szeroki',
        narrowMod: 'mod Wąski',
        inhibitorMod: 'Blokada',
        alignmentMod: 'Mod wyrównania osiowego',
        terrainAnalyzer: 'Analizator terenu',
        smallBattery: 'Mała bateria',
        batterySensor: 'Czujnik baterii',
        buttonRepeater: 'Przycisk Powtarzający',
        proximityRepeater: 'Powtarzacz zbliżeniowy',
        delayRepeater: 'Opóźnienie Powtórzen',
        countRepeater: 'Licznik Powtórzen',
        recreationalSphere: 'Kula Wypoczynkowa',
        largeRover: 'Duży łazik',
        paver: 'brukarz',
        drillMod3: 'Świder Mod 3',
        drillStrength3: 'Siła Świdra 3',
        fireworks: 'Ogine Sztuczne',
        fieldShelter: 'Schron polowy',
        portableOxygenator: 'Przenośny Natleniacz',
        holographicFigurine: 'Figurka holograficzna',
        mediumRover: 'Średni łazik',
        shelter: 'Schronienie',
        winch: 'wciągarka',
        autoExtractor: 'Auto-ekstraktor',
        probeScanner: 'Skaner sond',
        hydrazineThruster: 'Manewrowy Silnik Hydrazynowy',
        largeStorageSiloA: 'Duży silos magazynowy A',
        largeStorageSiloB: 'Duży silos magazynowy B',
        extraLargeShredder: 'Ekstra duża rozdrabniarka',
        drillStrength2: 'Siła Świdra 2',
        hydrazineJetPack: 'Plecak odrzutowy na hydrazynę',
        drillMod2: 'Świder Mod 2',
        mediumTPlatform: 'Średnia platforma',
        mediumBuggyHorn: 'Średni klakson',
        smallCanister: 'Mały pojemnik',
        powerSwitch: 'Przełącznik zasilania',
        automoton001: 'Automoton 001',
        automoton002: 'Automoton 002',
        cubicObject: 'Sześcianowy obiekt',
        stellarObject: 'Obiekt gwiazdowy',
        cosmigBauble: 'Kosmiczna ozdoba',
        scrap: 'Złom',
        event: 'Wydarzenie',
        full: 'Pełny',
        levelingBlock: 'Blok poziomujący',
        unlocked: 'Odblokowany',
        smallCamera: 'Mała kamera',
        smallTrumpetHorn: 'Mały róg trąbki',
        hoverboard: 'Hulajnoga powietrzna',
        largeExtendedPlatform: 'Duża rozszerzona platforma',
        largeActiveStorage: 'Duże aktywne magazynowanie',
        largeFogHorn: 'Duży róg mgłowy',
        vtol: 'VTOL',
        sourceVtol: 'Pionowy start i lądowanie (VTOL)',
        printTitle: 'Drukuj przedmioty',
        xlExtendedPlatform: 'Bardzo duża rozszerzona platforma',
        sourcePortableSmeltingFurnace: 'Przenośna piec do topienia',
        gravityGlobe: 'Kula grawitacyjna',
        easy: 'Łatwy',
        planetDetails: 'Szczegóły planety',
        size: 'Rozmiar',
        medium: 'Średni',
        difficulty: 'Trudność',
        dayNigthCycle: 'Cykl dnia/nocy',
        minutes: 'Minuty',
        sunPower: 'Energia słoneczna',
        windPower: 'Energia wiatrowa',
        location: 'Lokalizacja: ',
        caveLayer: 'Jaskini',
        mantleLayer: 'Płaszcza',
        small: 'Mały',
        grayPlains: 'Szare równiny',
        veryHigh: 'Bardzo wysokie',
        low: 'Niski',
        high: 'Wysoki',
        veryLow: 'Bardzo niski',
        purpleHills: 'Fioletowe wzgórza',
        mountains: 'Góry',
        icePlains: 'Lodowe równiny',
        hard: 'Trudny',
        veryHard: 'Bardzo trudny',
        
        // Long Names
        backpackPrinter: 'Drukarka plecakowa',
        smallPrinter: 'Mała drukarka',
        mediumPrinter: 'Średnia drukarka',
        largePrinter: 'Duża drukarka',
        soilCentrifuge: 'Wirówka Ziemna',
        chemistryLab: 'Laboratorium chemiczne',
        atmosphericCondenser: 'Kondensator Powietrza',
        tradePlatform: 'Platforma handlowa',
        smeltingFurnace: 'Piec do wytapiania',
        
        backpack: 'Plecak',
        sourceSmallPrinter: 'Mała Druk.',
        sourceMediumPrinter: 'Średnia Druk.',
        sourceLargePrinter: 'Duża Druk.',
        sourceChemistryLab: 'Lab. Chemiczne',
        sourceSoilCentrifuge: 'Wirówka Ziem.',
        sourceAtmosphericCondenser: 'Kon. Powietrza',
        sourceTradePlatform: 'Plat. Handlowa',
        sourceSmeltingFurnace: 'Piecyk Wytap.',
}