export default {
    // App commun texts
    welcome: 'A MANEIRA MAIS FÁCIL\nDE USAR\nA ASTROPEDIA',
    userIdentification: 'Qual o nome do seu\nAstronauta?',
    language: 'Idioma: ',
    whatYouWant: 'Não vê o que quer? ',
    contactUs: 'Contate-nos',
    contactUsDefaultName: 'Astroneer Player',
    contactUsMail: 'noreply',
    contactUsMessageFrom: '\n\n\nMensagem de: ',
    contactUsMessageReply: '\nResponder para: ',
    contactUsWarnning: 'Você precisa incluir uma mensagem!',
    contactUsPlaceholderEmail: 'E-mail',
    contactUsPlaceholderName: 'Nome',
    contactUsPlaceholderMessage: 'Mensagem',
    avatar: 'Avatar: ',
    name: 'Nome: ',
    aboutUs: 'Sobre Nós',
    aboutUsCredit: 'Créditos',
    aboutUsDeveloped: 'Desenvolvido por MIDDLEWARE DEV',
    aboutUsDesign: 'Design',
    aboutUsThanks: 'Agradecimentos Especiais ',
    aboutUsTranslation: 'Traduções',
    warningTitle: 'Aviso',
    warningMessage: 'As mudanças só serão efetivas após você reiniciar a Astropedia',
    warningButton: 'Ok',

    // Titles
    mainTitle: 'Astropedia',
    planetsTitle: 'Planetas',
    resourcesTitle: 'Recursos',
    favoritesTitle: 'Favoritos',
    naturalResourcesTitle: 'recursos naturais',
    atmosphericResourcesTitle: 'recursos atmosféricos',
    sourceTitle: 'Fonte',
    usesTitle: 'Usos',
    printers: 'Impressoras',

    // Planet's names
    sylva: 'Sylva',
    desolo: 'Desolo',
    calidor: 'Calidor',
    vesania: 'Vesania',
    novus: 'Novus',
    glacio: 'Glacio',
    atrox: 'Atrox',

    // Resource's names
    ammonium: 'Amônia',
    astronium: 'Astrônio',
    clay: 'Argila',
    compound: 'Composto',
    graphite: 'Grafite',
    hematite: 'Hematita',
    laterite: 'Laterita',
    lithium: 'Lítio',
    malachite: 'Malaquita',
    organic: 'Orgânico',
    quartz: 'Quartzo',
    resin: 'Resina',
    sphalerite: 'Blenda',
    titanite: 'Titanita',
    wolframite: 'Volframita',
    aluminum: 'Alumínio',
    carbon: 'Carbono',
    ceramic: 'Cerâmica',
    copper: 'Cobre',
    glass: 'Vidro',
    iron: 'Ferro',
    titanium: 'Titânio',
    tungsten: 'Tungstênio',
    zinc: 'Zinco',
    argon: 'Argônio',
    helium: 'Hélio',
    hydrogen: 'Hidrogênio',
    methane: 'Metano',
    nitrogen: 'Nitrogênio',
    sulfur: 'Enxofre',
    aluminumAlloy: 'Liga Alumínio',
    diamond: 'Diamante',
    explosivePowder: 'Pó Explosivo',
    hydrazine: 'Hidrazina',
    graphene: 'Grafeno',
    nanocarbonAlloy: 'Nanocarbono',
    plastic: 'Plástico',
    rubber: 'Borracha',
    silicone: 'Silicone',
    steel: 'Aço',
    titaniumAlloy: 'Liga de Titânio',
    tungstenCarbide: 'Carb. Tungs...',

    // Sources and Items name
    sourceAllPlanets: 'Todos os Planetas',
    solidFuelThruster: 'Motor de Combustível Sólido',
    exoChip: 'Chip Exo',
    packager: 'Embalador',
    solidFuelJumpJet: 'Propulsor de Combustível Sólido',
    dynamite: 'Dinamite',
    smallGenerator: 'Gerador Pequeno',
    tether: 'Cabos',
    roverSeat: 'Assento de Veículo',
    trailer: 'Trailer',
    researchChamber: 'Câmara de Pesquisa',
    largeRoverSeat: 'Assento Grande de Veículo',
    buggy: 'Buggy',
    splitter: 'Divisor',
    autoArm: 'Braço de Auto',
    mediumBattery: 'Bateria Média',
    rtg: 'RTG',
    glowsticks: 'Bastões Luminosos',
    beacon: 'Sinal',
    storageSensor: 'Sensor de Depósito',
    mediumSensorArch: 'Sensor em Arco Médio',
    largeSensorRing: 'Sensor em Anel Grande',
    largeSensorHoopA: 'Sensor em Aro Grande A',
    largeSensorHoopB: 'Sensor em Aro Grande B',
    xlSensorArch: 'Sensor em Arco XG',
    xlSensorCanopy: 'Sensor em Dossel XG',
    xlSensorHoopA: 'Sensor em Aro XG A',
    xlSensorHoopB: 'Sensor em Aro XG B',
    canister: 'Recipiente Pequeno',
    oxygenFilter: 'Filtros de Oxigênio',
    mediumStorage: 'Armazenagem Média',
    mediumPlatformA: 'Plataforma Média A',
    mediumPlatformB: 'Plataforma Média B',
    mediumPlatformC: 'Plataforma Média C',
    largePlatformA: 'Plataforma Grande A',
    largePlatformB: 'Plataforma Grande B',
    oxygenator: 'Oxygenator',
    mediumGenerator: 'Gerador Médio',
    mediumWindTurbine: 'Turbina Eólica Média',
    tractor: 'Trator',
    largeTPlatform: 'Plataforma-T Grande',
    smallShuttle: 'Nave Pequena',
    landingPad: 'Pista de Pouso',
    sourceAluminumAlloy: 'Liga de Alumínio',
    sourceExplosivePowder: 'Pó Explosivo',
    sourceNanocarbonAlloy: 'Liga de Nanocarbono',
    sourceTungstenCarbide: 'Carboneto de Tungstênio',
    drillMod1: 'Mód de Broca 1',
    smallWindTurbine: 'Turbina Eólica Pequena',
    tallPlatform: 'Plataforma Alta',
    tallStorage: 'Armazenagem Alta',
    drillStrength1: 'Força de Broca 1',
    exoRequestPlatform: 'Plataforma de Pedidos EXO',
    largeWindTurbine: 'Turbina Eólica Grande',
    largePlatformC: 'Plataforma Grande C',
    largeCurvedPlatform: 'Plataforma Grande Curvada',
    largeStorage: 'Armazenagem Grande',
    xlWindTurbine: 'Turbina Eólica GG',
    extraLargePlatformA: 'Plataforma Extra Grande A',
    extraLargeCurvedPlatform: 'Plataforma Extra Grande Curvada',
    extraLargeStorage: 'Armazenamento Extra Grande',
    mediumShuttle: 'Nave Média',
    largeShuttle: 'Nave Grande',
    worklight: 'Luz de Trabalho',
    smallSolarPanel: 'Solar Pequena',
    extenders: 'Extensores',
    mediumSolarPanel: 'Solar Médio',
    powerSensor: 'Sensor de Energia',
    solarArray: 'Painel Solar',
    oxygenTank: 'Tanque de Oxigênio',
    mediumResourceCanister: 'Recipiente de Recursos Médio',
    mediumFluidSoilCanister: 'Recipiente Médio de Líquido & Solo',
    mediumGasCanister: 'Recipiente Médio de Gás',
    largeResourceCaniester: 'Recipiente de Recursos Grande',
    largeSolarPanel: 'Painel Solar Grande',
    mediumShredder: 'Triturador Médio',
    largeShredder: 'Triturador Grande',
    extraLargePlatformB: 'Plataforma Extra Grande B',
    extraLargePlatformC: 'Plataforma Extra Grande C',
    figurinePlatform: 'Plataforma de Estatueta',
    crane: 'Guindaste',
    largeResourceCanister: 'Recipiente de Recursos Grande',
    mediumStorageSilo: 'Torre de Armazenagem Média',
    floodlight: 'Holofote',
    powerCells: 'Células de Energias',
    wideMod: 'Mod Amplo',
    alignmentMod: 'Modificação de Alinhamento',
    inhibitorMod: 'Inibidor',
    boostMod: 'Modificador de Velocidade',
    narrowMod: 'Mod Estreito',
    terrainAnalyzer: 'Analisador de Terreno',
    smallBattery: 'Bateria Pequena',
    batterySensor: 'Sensor de Bateria',
    buttonRepeater: 'Repetidor de Botão',
    proximityRepeater: 'Repetidor de Proximidade',
    delayRepeater: 'Repetir Atraso',
    countRepeater: 'Repitir contagem',
    recreationalSphere: 'Esfera Recreativa',
    largeRover: 'Quadriciclo Grande',
    paver: 'Pavimentadora',
    drillMod3: 'Mód de Broca 3',
    drillStrength3: 'Força de Broca 3',
    fireworks: 'Fogos de Artifício',
    fieldShelter: 'Abrigo de Campo',
    portableOxygenator: 'Oxigenador Portátil',
    holographicFigurine: 'Estatueta Holográfica',
    mediumRover: 'Quadriciclo Médio',
    shelter: 'Abrigo',
    winch: 'Guincho',
    autoExtractor: 'Auto Extrator',
    probeScanner: 'Leitor de Sonda',
    hydrazineThruster: 'Propulsor de Hidrazina',
    largeStorageSiloA: 'Torre de Armazenamento Grande A',
    largeStorageSiloB: 'Torre de Armazenamento Grande B',
    extraLargeShredder: 'Triturador Extra Grande',
    drillStrength2: 'Força de Broca 2',
    hydrazineJetPack: 'Mochila de Hidrazina',
    drillMod2: 'Mód Broca 2',
    mediumTPlatform: 'Plataforma T Média',
    mediumBuggyHorn: 'Buzina de Buggy Médio',
    smallCanister: 'Recipiente Pequeno',
    powerSwitch: 'Interruptor de Energia',
    automoton001: 'Automaton 001',
    automoton002: 'Automaton 002',
    cubicObject: 'Objeto Cúbico',
    stellarObject: 'Objeto Estelar',
    cosmigBauble: 'Bola Cósmica',
    scrap: 'Sucata',
    event: 'Evento',
    full: 'Cheio',
    levelingBlock: 'Bloco de Nivelamento',
    unlocked: 'Desbloqueado',
    smallCamera: 'Câmera Pequena',
    smallTrumpetHorn: 'Buzina de Trompete Pequena',
    hoverboard: 'Skate Voador',
    largeExtendedPlatform: 'Plataforma Grande Estendida',
    largeActiveStorage: 'Armazenamento Grande Ativo',
    largeFogHorn: 'Buzina de Neblina Grande',
    vtol: 'VTOL',
    sourceVtol: 'Vertical Take-Off and Landing (VTOL)',
    printTitle: 'Imprimir os Itens',
    xlExtendedPlatform: 'Plataforma Extra Grande Estendida',
    sourcePortableSmeltingFurnace: 'Forno de Fundição Portátil',
    gravityGlobe: 'Globo Gravitacional',
    easy: 'Fácil',
    planetDetails: 'Detalhes do Planeta',
    size: 'Tamanho',
    medium: 'Médio',
    difficulty: 'Dificuldade',
    dayNigthCycle: 'Ciclo Dia/Noite',
    minutes: 'Minutos',
    sunPower: 'Energia Solar',
    windPower: 'Energia Eólica',
    location: 'Localização: ',
    caveLayer: 'Caverna',
    mantleLayer: 'Manto',
    small: 'Pequeno',
    grayPlains: 'Planícies Cinzentas',
    veryHigh: 'Muito Alta',
    low: 'Baixa',
    high: 'Alta',
    veryLow: 'Muito Baixa',
    purpleHills: 'Colinas Roxas',
    mountains: 'Montanhas',
    icePlains: 'Planícies de Gelo',
    hard: 'Difícil',
    veryHard: 'Muito Difícil',

    // Long Names
    backpackPrinter: 'Impressora da Mochila',
    smallPrinter: 'Impressora Pequena',
    mediumPrinter: 'Impressora Média',
    largePrinter: 'Impressora Grande',
    soilCentrifuge: 'Centrífuga de Solo',
    chemistryLab: 'Laboratório de Química',
    atmosphericCondenser: 'Condensador Atmosférico',
    tradePlatform: 'Plataforma de Troca',
    smeltingFurnace: 'Fundível',

    backpack: 'Mochila',
    sourceSmallPrinter: 'Impressora P',
    sourceMediumPrinter: 'Impressora M',
    sourceLargePrinter: 'Impressora G',
    sourceSoilCentrifuge: 'Centrífuga',
    sourceChemistryLab: 'Laboratório',
    sourceAtmosphericCondenser: 'Condensador',
    sourceTradePlatform: 'Plat. de Troca',
    sourceSmeltingFurnace: 'Fundível',
};