export default {
    // App commun texts
    welcome: "A MANEIRA MAIS FÁCIL\nDE USAR\nA ASTROPEDIA",
    userIdentification: "Qual é o seu\nnome de Astroneer?",
    language: "Idioma: ",
    whatYouWant: "Não encontrou o que queria?",
    contactUs: "Fale Conosco",
    contactUsDefaultName: "Jogador de Astroneer",
    contactUsMail: "noreply",
    contactUsMessageFrom: "\n\n\nMensagem de: ",
    contactUsMessageReply: "\nResponder para: ",
    contactUsWarning: "Você precisa incluir uma mensagem!",
    contactUsPlaceholderEmail: "Email",
    contactUsPlaceholderName: "Nome",
    contactUsPlaceholderMessage: "Mensagem",
    avatar: "Avatar: ",
    name: "Nome: ",
    aboutUs: "Sobre Nós",
    aboutUsCredit: "Créditos",
    aboutUsDeveloped: "Desenvolvido por MIDDLEWARE DEV",
    aboutUsDesign: "Design",
    aboutUsThanks: "Agradecimentos Especiais a",
    aboutUsTranslation: "Traduções",
    warningTitle: "Aviso",
    warningMessage: "As alterações só terão efeito após reiniciar a Astropedia",
    warningButton: "Ok",

    // Titles
    mainTitle: "Astropedia",
    planetsTitle: "Planetas",
    resourcesTitle: "Recursos",
    favoritesTitle: "Favoritos",
    naturalResourcesTitle: "Recursos Naturais",
    atmosphericResourcesTitle: "Recursos Atmosféricos",
    sourceTitle: "Fonte",
    usesTitle: "Usos",
    printers: "Impressoras",

    // Planet's names
    sylva: "Sylva",
    desolo: "Desolo",
    calidor: "Calidor",
    vesania: "Vesania",
    novus: "Novus",
    glacio: "Glacio",
    atrox: "Atrox",

    //Basic Resource's names
    ammonium: "Amônia",
    astronium: "Astrônio",
    clay: "Argila",
    compound: "Composto",
    graphite: "Grafite",
    hematite: "Hematita",
    laterite: "Laterita",
    lithium: "Lítio",
    malachite: "Malaquita",
    organic: "Orgânico",
    quartz: "Quartzo",
    resin: "Resina",
    sphalerite: "Esfaerita",
    titanite: "Titanita",
    wolframite: "Wolframita",
    aluminum: "Alumínio",
    carbon: "Carbono",
    ceramic: "Cerâmica",
    copper: "Cobre",
    glass: "Vidro",
    iron: "Ferro",
    titanium: "Titânio",
    tungsten: "Tungstênio",
    zinc: "Zinco",

    //Gas names
    argon: "Argônio",
    helium: "Hélio",
    hydrogen: "Hidrogênio",
    methane: "Metano",
    nitrogen: "Nitrogênio",
    sulfur: "Enxofre",

    //Compost Resourse name
    aluminumAlloy: "Liga de Alumínio",
    diamond: "Diamante",
    explosivePowder: "Pó Explosivo",
    hydrazine: "Hidrazina",
    graphene: "Grafeno",
    nanocarbonAlloy: "Liga de Nanocarbono",
    plastic: "Plástico",
    rubber: "Borracha",
    silicone: "Silicone",
    steel: "Aço",
    titaniumAlloy: "Liga de Titânio",
    tungstenCarbide: "Carboneto de Tungstênio",

    // Sources and Items name
    sourceAllPlanets: "Todos os Planetas",
    solidFuelThruster: "Propulsor de Combustível Sólido",
    exoChip: "Chip Exo",
    packager: "Empacotador",
    solidFuelJumpJet: "Propulsor de Salto de Combustível Sólido",
    dynamite: "Dinamite",
    smallGenerator: "Gerador Pequeno",
    tether: "Cabo",
    roverSeat: "Assento do Rover",
    trailer: "Reboque",
    researchChamber: "Câmara de Pesquisa",
    largeRoverSeat: "Assento Grande do Rover",
    buggy: "Buggy",
    splitter: "Divisor",
    autoArm: "Braço Automático",
    mediumBattery: "Bateria Média",
    rtg: "RTG",
    glowsticks: "Bastões de Luz",
    beacon: 'Sinal',

    storageSensor: "Sensor de Armazenamento",
    mediumSensorArch: "Arco de Sensor Médio",
    largeSensorRing: "Anel de Sensor Grande",
    largeSensorHoopA: "Aro de Sensor Grande A",
    largeSensorHoopB: "Aro de Sensor Grande B",
    xlSensorArch: "Arco de Sensor XL",
    xlSensorCanopy: "Toldo de Sensor XL",
    xlSensorHoopA: "Aro de Sensor XL A",
    xlSensorHoopB: "Aro de Sensor XL B",
    canister: "Recipiente",
    oxygenFilter: "Filtro de Oxigênio",
    mediumStorage: "Armazenamento Médio",
    mediumPlatformA: "Plataforma Média A",
    mediumPlatformB: "Plataforma Média B",
    mediumPlatformC: "Plataforma Média C",
    largePlatformA: "Plataforma Grande A",
    largePlatformB: "Plataforma Grande B",
    oxygenator: "Oxigenador",
    mediumGenerator: "Gerador Médio",
    mediumWindTurbine: "Turbina Eólica Média",
    tractor: "Trator",

    largeTPlatform: "Grande Plataforma T",
    smallShuttle: "Nave Pequena",
    landingPad: "Plataforma de Pouso",
    drillMod1: "Módulo de Perfuração 1",
    smallWindTurbine: "Pequena Turbina Eólica",
    tallPlatform: "Plataforma Alta",
    tallStorage: "Armazenamento Alto",
    drillStrength1: "Força de Perfuração 1",
    exoRequestPlatform: "Plataforma de Requisição Exo",
    largeWindTurbine: "Grande Turbina Eólica",
    largePlatformC: "Grande Plataforma C",
    largeCurvedPlatform: "Grande Plataforma Curva",
    largeStorage: "Armazenamento Grande",
    xlWindTurbine: "Turbina Eólica XL",
    extraLargePlatformA: "Plataforma Extra Grande A",
    extraLargeCurvedPlatform: "Plataforma Extra Grande Curva",
    extraLargeStorage: "Armazenamento Extra Grande",
    mediumShuttle: "Nave Média",
    largeShuttle: "Nave Grande",
    worklight: "Luz de Trabalho",
    smallSolarPanel: "Pequeno Painel Solar",
    extenders: "Extensor",
    mediumSolarPanel: "Médio Painel Solar",
    powerSensor: "Sensor de Energia",
    solarArray: "Matriz Solar",
    oxygenTank: "Tanque de Oxigênio",

    mediumResourceCanister: "Recipiente de Recursos Médio",
    mediumFluidSoilCanister: "Recipiente de Fluido e Solo Médio",
    mediumGasCanister: "Recipiente de Gás Médio",
    largeResourceCaniester: "Recipiente de Recursos Grande",
    largeSolarPanel: "Painel Solar Grande",
    mediumShredder: "Triturador Médio",
    largeShredder: "Triturador Grande",
    extraLargePlatformB: "Plataforma Extra Grande B",
    extraLargePlatformC: "Plataforma Extra Grande C",
    figurinePlatform: "Plataforma de Figurinhas",
    crane: "Guindaste",
    largeResourceCanister: "Recipiente de Recursos Grande",
    mediumStorageSilo: "Silo de Armazenamento Médio",
    floodlight: "Refletor",
    powerCells: "Células de Energia",
    wideMod: "Modificação Larga",
    alignmentMod: "Modificação de Alinhamento",
    inhibitorMod: "Modificação Inibidora",
    boostMod: "Modificação de Impulso",
    narrowMod: "Modificação Estreita",
    terrainAnalyzer: "Analisador de Terreno",
    smallBattery: "Bateria Pequena",
    batterySensor: "Sensor de Bateria",
    buttonRepeater: "Repetidor de Botão",
    proximityRepeater: "Repetidor de Proximidade",
    delayRepeater: "Repetidor de Atraso",
    countRepeater: "Repetidor de Contagem",
    recreationalSphere: "Esfera Recreativa",
    largeRover: "Rover Grande",
    paver: "Pavimentadora",
    drillMod3: "Modificação de Perfuração 3",

    drillStrength3: "Força de Perfuração 3",
    fireworks: "Fogos de Artifício",
    fieldShelter: "Abrigo de Campo",
    portableOxygenator: "Oxigenador Portátil",
    holographicFigurine: "Figura Holográfica",
    mediumRover: "Rover Médio",
    shelter: "Abrigo",
    winch: "Guincho",
    autoExtractor: "Extrator Automático",
    probeScanner: "Scanner de Sondas",
    hydrazineThruster: "Propulsor de Hidrazina",
    largeStorageSiloA: "Silo de Armazenamento Grande A",
    largeStorageSiloB: "Silo de Armazenamento Grande B",
    extraLargeShredder: "Triturador Extra Grande",
    drillStrength2: "Força de Perfuração 2",
    hydrazineJetPack: "Mochila a Jato de Hidrazina",
    drillMod2: "Modificação de Perfuração 2",
    mediumTPlatform: "Plataforma T Média",
    mediumBuggyHorn: "Buzina do Buggy Média",
    smallCanister: "Recipiente Pequeno",
    powerSwitch: "Interruptor de Energia",
    automoton001: "Automato 001",
    automoton002: "Automato 002",
    cubicObject: "Objeto Cúbico",
    stellarObject: "Objeto Estelar",
    cosmigBauble: "Bola Cósmica",
    scrap: "Sucata",
    event: "Evento",
    full: "Completo",

    levelingBlock: "Bloco de Nivelamento",
    unlocked: "Desbloqueado",
    smallCamera: "Câmera Pequena",
    smallTrumpetHorn: "Pequeno Trompete",
    hoverboard: "Hoverboard",
    largeExtendedPlatform: "Plataforma Ampliada Grande",
    largeActiveStorage: "Armazenamento Ativo Grande",
    largeFogHorn: "Grande Buzina de Neblina",
    vtol: "VTOL",
    sourceVtol: "Decolagem e Pouso Vertical (VTOL)",
    printTitle: "Imprimir os Itens",
    xlExtendedPlatform: "Plataforma Ampliada XL",
    sourcePortableSmeltingFurnace: "Forno de Fusão Portátil",
    gravityGlobe: "Globo de Gravidade",
    easy: "Fácil",
    planetDetails: "Detalhes do Planeta",
    size: "Tamanho",
    medium: "Médio",
    difficulty: "Dificuldade",
    dayNigthCycle: "Ciclo Dia/Noite",
    minutes: "Minutos",
    sunPower: "Energia Solar",
    windPower: "Energia Eólica",
    location: "Localização: ",
    caveLayer: "Camada de Caverna",
    mantleLayer: "Camada do Manto",
    small: "Pequeno",
    grayPlains: "Planícies Cinzentas",
    veryHigh: "Muito Alto",
    low: "Baixo",
    high: "Alto",
    veryLow: "Muito Baixo",
    purpleHills: "Colinas Roxas",
    mountains: "Montanhas",
    icePlains: "Planícies de Gelo",
    hard: "Difícil",
    veryHard: "Muito Difícil",

    // Long Names
    backpackPrinter: 'Impressora da Mochila',
    smallPrinter: "Impressora Pequena",
    mediumPrinter: "Impressora Média",
    largePrinter: "Impressora Grande",
    soilCentrifuge: "Centrífuga de Solo",
    chemistryLab: "Laboratório de Química",
    atmosphericCondenser: "Condensador Atmosférico",
    tradePlatform: 'Plataforma de Troca',
    smeltingFurnace: 'Fundível',

    // Printers table
    craftedAt: "Fabricado em",
    recipe: "Receita",
    unlockCost: "Custo de Desbloqueio",
    powerConsumption: "Consumo de Energia",
    "-": "-"
};