export default {
    //App commun texts
    welcome: 'O JEITO MAIS FACIL\nDE USAR\nA ASTROPÉDIA',
    userIdentification: 'Qual o nome do seu\nAstronauta?',

    //Titles
    mainTitle: 'Astropédia',
    planetsTitle: 'Planetas',
    resourcesTitle: 'Recursos',
    favoritesTitle: 'Favoritos',
    naturalResourcesTitle: 'Recursos Naturais',
    atmosphericResourcesTitle: 'Recursos Atmosféricos',
    sourceTitle: 'Obtido de',
    usesTitle: 'Usos',

    //Planet's names
    sylva: 'Sylva',
    desolo: 'Desolo',
    calidor: 'Calidor',
    vesania: 'Vesania',
    novus: 'Novus',
    glacio: 'Glacio',
    atrox: 'Atrox',

    //Resource's names
    ammonium: 'Amônia',
    astronium: 'Astrônio',
    clay: 'Argila',
    compound: 'Composto',
    graphite: 'Grafite',
    hematite: 'Hematita',
    laterite: 'Laterita',
    lithium: 'Lítio',
    malachite: 'Malaquita',
    organic: 'Orgânico',
    quartz: 'Quartzo',
    resin: 'Resina',
    sphalerite: 'Blenda',
    titanite: 'Titanita',
    wolframite: 'Volframita',
    aluminum: 'Alumínio',
    carbon: 'Carbono',
    ceramic: 'Cerâmica',
    copper: 'Cobre',
    glass: 'Vidro',
    iron: 'Ferro',
    titanium: 'Titânio',
    tungsten: 'Tungstênio',
    zinc: 'Zinco',
    argon: 'Argônio',
    helium: 'Hélio',
    hydrogen: 'Hidrogênio',
    methane: 'Metano',
    nitrogen: 'Nitrogênio',
    sulfur: 'Enxofre',
    aluminumAlloy: 'Liga Alumínio',
    diamond: 'Diamante',
    explosivePowder: 'Pó Explosivo',
    hydrazine: 'Hidrazina',
    graphene: 'Grafeno',
    nanocarbonAlloy: 'Nanocarbono',
    plastic: 'Plástico',
    rubber: 'Borracha',
    silicone: 'Silicone',
    steel: 'Aço',
    titaniumAlloy: 'Liga de Titânio',
    tungstenCarbide: 'Carb. Tungs...',

    //Sources and Items name
    sourceAllPlanets: 'Todos os Planetas',
    soilCentrifuge: 'Centrífuga de Solo',
    tradePlatform: 'Plataforma de Troca',
    smallPrinter: 'Impressora Pequena',
    solidFuelThruster: 'Motor de Combustível Sólido',
    chemistryLab: 'Laboratório de Química',
    exoChip: 'Chip Exo',
    packager: 'Embalador',
    solidFuelJumpJet: 'Propulsor de Combustível Sólido',
    dynamite: 'Dinamite',
    smeltingFurnace: 'Fundível',
    backpackPrinter: 'Impressora da Mochila',
    smallGenerator: 'Gerador Pequeno',
    tether: 'Cabos',
    roverSeat: 'Assento de Veículo',
    mediumPrinter: 'Impressora Média',
    trailer: 'Trailer',
    researchChamber: 'Câmara de Pesquisa',
    largePrinter: 'Impressora Grande',
    largeRoverSeat: 'Assento Grande de Veículo',
    buggy: 'Buggy',
    splitter: 'Divisor',
    autoArm: 'Braço de Auto',
    mediumBattery: 'Bateria Média',
    rtg: 'RTG',
    glowsticks: 'Bastões Luminosos',
    beacon: 'Sinal',
    storageSensor: 'Sensor de Depósito',
    mediumSensorArch: 'Sensor em Arco Médio',
    largeSensorRing: 'Sensor em Anel Grande',
    largeSensorHoopA: 'Sensor em Aro Grande A',
    largeSensorHoopB: 'Sensor em Aro Grande B',
    xlSensorArch: 'Sensor em Arco XG',
    xlSensorCanopy: 'Sensor em Dossel XG',
    xlSensorHoopA: 'Sensor em Aro XG A',
    xlSensorHoopB: 'Sensor em Aro XG B',
    canister: 'Recipiente Pequeno',
    oxygenFilter: 'Filtros de Oxigênio',
    mediumStorage: 'Armazenagem Média',
    mediumPlatformA: 'Plataforma Média A',
    mediumPlatformB: 'Plataforma Média B',
    mediumPlatformC: 'Plataforma Média C',
    largePlatformA: 'Plataforma Grande A',
    largePlatformB: 'Plataforma Grande B',
    oxygenator: 'Oxigenador',
    mediumGenerator: 'Gerador Médio',
    mediumWindTurbine: 'Turbina Eólica Média',
    tractor: 'Trator',
    largeTPlatform: 'Plataforma-T Grande',
    smallShuttle: 'Nave Pequena',
    landingPad: 'Pista de Pouso',
    sourceAluminumAlloy: 'Liga de Alumínio',
    sourceExplosivePowder: 'Pó Explosivo',
    sourceNanocarbonAlloy: 'Liga de Nanocarbono',
    sourceTungstenCarbide: 'Carboneto de Tungstênio',
    drillMod1: 'Mód de Broca 1',
    smallWindTurbine: 'Turbina Eólica Pequena',
    tallPlatform: 'Plataforma Alta',
    tallStorage: 'Armazenagem Alta',
    drillStrength1: 'Força de Broca 1',
    exoRequestPlatform: 'Plataforma de Pedidos EXO',
    largeWindTurbine: 'Turbina Eólica Grande',
    largePlatformC: 'Plataforma Grande C',
    largeCurvedPlatform: 'Plataforma Grande Curvada',
    largeStorage: 'Armazenagem Grande',
    xlWindTurbine: 'Turbina Eólica GG',
    extraLargePlatformA: 'Plataforma Extra Grande A',
    extraLargeCurvedPlatform: 'Plataforma Extra Grande Curvada',
    extraLargeStorage: 'Armazenamento Extra Grande',
    mediumShuttle: 'Nave Média',
    largeShuttle: 'Nave Grande',
    worklight: 'Luz de Trabalho',
    smallSolarPanel: 'Solar Pequena',
    extenders: 'Extensores',
    mediumSolarPanel: 'Solar Médio',
    powerSensor: 'Sensor de Energia',
    solarArray: 'Painel Solar',
    oxygenTank: 'Tanque de Oxigênio',
    mediumResourceCanister: 'Recipiente de Recursos Médio',
    mediumFluidSoilCanister: 'Recipiente Médio de Líquido & Solo',
    mediumGasCanister: 'Recipiente Médio de Gás',
    atmosphericCondenser: 'Condensador Atmosférico',
    largeResourceCaniester: 'Recipiente de Recursos Grande',
    largeSolarPanel: 'Painel Solar Grande',
    mediumShredder: 'Triturador Médio',
    largeShredder: 'Triturador Grande',
    extraLargePlatformB: 'Plataforma Extra Grande B',
    extraLargePlatformC: 'Plataforma Extra Grande C',
    figurinePlatform: 'Plataforma de Estatueta',
    crane: 'Guindaste',
    largeResourceCanister: 'Recipiente de Recursos Grande',
    mediumStorageSilo: 'Torre de Armazenagem Média',
    floodlight: 'Holofote',
    powerCells: 'Células de Energias',
    wideMod: 'Mod Amplo',
    alignmentMod: 'Modificação de Alinhamento',
    inhibitorMod: 'Inibidor',
    boostMod: 'Modificador de Velocidade',
    narrowMod: 'Mod Estreito',
    terrainAnalyzer: 'Analisador de Terreno',
    smallBattery: 'Bateria Paquena',
    batterySensor: 'Sensor de Bateria',
    buttonRepeater: 'Repetidor de Botão',
    proximityRepeater: 'Repetidor de Proximidade',
    delayRepeater: 'Repetir Atraso',
    countRepeater: 'Repitir contagem',
    recreationalSphere: 'Esfera Recreativa',
    largeRover: 'Quadriciclo Grande',
    paver: 'Pavimentadora',
    drillMod3: 'Mód de Broca 3',
    drillStrength3: 'Força de Broca 3',
    fireworks: 'Fogos de Artifício',
    fieldShelter: 'Abrigo de Campo',
    portableOxygenator: 'Oxigenador Portátil',
    holographicFigurine: 'Estatueta Holográfica',
    mediumRover: 'Quadriciclo Médio',
    shelter: 'Abrigo',
    winch: 'Guincho',
    autoExtractor: 'Extrator de Auto',
    probeScanner: 'Leitor de Sonda',
    hydrazineThruster: 'Propulsor de Hidrazina',
    largeStorageSiloA: 'Torre de Armazenamento Grande A',
    largeStorageSiloB: 'Torre de Armazenamento Grande B',
    extraLargeShredder: 'Triturador Extra Grande',
    drillStrength2: 'Força da Broca 2',
    hydrazineJetPack: 'Propulsor a Jato de Hidrazina',
    drillMod2: 'Mód de Broca 2'
}