export default {
    //App commun texts
    welcome: "ЛЕГЧАЙШИЙ СПОСОБ\nИСПОЛЬЗОВАТЬ\nАСТРОПЕДИЮ",
    userIdentification: "Какое ваше\nимя в Astroneer?",
    language: "Язык: ",
    whatYouWant: "Не видите, что хотите?",
    contactUs: "Свяжитесь с нами",
    contactUsDefaultName: "Игрок Astroneer",
    contactUsMail: "noreply",
    contactUsMessageFrom: "\n\n\nСообщение от: ",
    contactUsMessageReply: "\nОтветить на: ",
    contactUsWarning: "Необходимо включить сообщение!",
    contactUsPlaceholderEmail: "Электронная почта",
    contactUsPlaceholderName: "Имя",
    contactUsPlaceholderMessage: "Сообщение",
    avatar: "Аватар: ",
    name: "Имя: ",
    aboutUs: "О нас",
    aboutUsCredit: "Благодарности",
    aboutUsDeveloped: "Разработано MIDDLEWARE DEV",
    aboutUsDesign: "Дизайн",
    aboutUsThanks: "Особая благодарность",
    aboutUsTranslation: "Переводы",
    warningTitle: "Предупреждение",
    warningMessage: "Изменения вступят в силу только после перезапуска Астропедии",
    warningButton: "Ок",

    //Titles
    mainTitle: "Астропедия",
    planetsTitle: "Планеты",
    resourcesTitle: "Ресурсы",
    favoritesTitle: "Избранное",
    naturalResourcesTitle: "Природные ресурсы",
    atmosphericResourcesTitle: "Атмосферные ресурсы",
    sourceTitle: "Источник",
    usesTitle: "Использование",
    printers: "Принтеры",

    //Planet's names
    sylva: "Сильва",
    desolo: "Десоло",
    calidor: "Калидор",
    vesania: "Везания",
    novus: "Новус",
    glacio: "Глейсио",
    atrox: "Атрокс",    

    //Basic Resource's names
    ammonium: "Аммоний",
    astronium: "Астроний",
    clay: "Глина",
    compound: "Соединение",
    graphite: "Графит",
    hematite: "Гематит",
    laterite: "Латерит",
    lithium: "Литий",
    malachite: "Малахит",
    organic: "Органический",
    quartz: "Кварц",
    resin: "Смола",
    sphalerite: "Сфалерит",
    titanite: "Титанит",
    wolframite: "Вольфрамит",
    aluminum: "Алюминий",
    carbon: "Углерод",
    ceramic: "Керамика",
    copper: "Медь",
    glass: "Стекло",
    iron: "Железо",
    titanium: "Титан",
    tungsten: "Вольфрам",
    zinc: "Цинк",

    //Gas names
    argon: "Аргон",
    helium: "Гелий",
    hydrogen: "Водород",
    methane: "Метан",
    nitrogen: "Азот",
    sulfur: "Сера",
    
    //Compost Resourse name
    aluminumAlloy: "Алюминиевый сплав",
    diamond: "Алмаз",
    explosivePowder: "Взрывчатый порошок",
    hydrazine: "Гидразин",
    graphene: "Графен",
    nanocarbonAlloy: "Наноуглеродный сплав",
    plastic: "Пластик",
    rubber: "Резина",
    silicone: "Силикон",
    steel: "Сталь",
    titaniumAlloy: "Титановый сплав",
    tungstenCarbide: "Карбид вольфрама",

    //Sources and Items name
    sourceAllPlanets: "Все Планеты",
    solidFuelThruster: "Твердотопливный Двигатель",
    exoChip: "Эзо Чип",
    packager: "Упаковщик",
    solidFuelJumpJet: "Твердотопливный Реактивный Ранец",
    dynamite: "Динамит",
    smallGenerator: "Малый Генератор",
    tether: "Трос",
    roverSeat: "Сиденье Ровера",
    trailer: "Трейлер",
    researchChamber: "Исследовательская Камера",
    largeRoverSeat: "Большое Сиденье Ровера",
    buggy: "Багги",
    splitter: "Разветвитель",
    autoArm: "Автоматическая Рука",
    mediumBattery: "Средняя Батарея",
    rtg: "РИТЭГ",
    glowsticks: "Светящиеся Палочки",
    beacon: "Маяк",

    storageSensor: "Датчик Хранилища",
    mediumSensorArch: "Средняя Арка Датчика",
    largeSensorRing: "Большое Кольцо Датчика",
    largeSensorHoopA: "Большая Обруч Датчика A",
    largeSensorHoopB: "Большая Обруч Датчика B",
    xlSensorArch: "XL Арка Датчика",
    xlSensorCanopy: "XL Навес Датчика",
    xlSensorHoopA: "XL Обруч Датчика A",
    xlSensorHoopB: "XL Обруч Датчика B",
    canister: "Канистра",
    oxygenFilter: "Фильтр Кислорода",
    mediumStorage: "Среднее Хранилище",
    mediumPlatformA: "Средняя Платформа A",
    mediumPlatformB: "Средняя Платформа B",
    mediumPlatformC: "Средняя Платформа C",
    largePlatformA: "Большая Платформа A",
    largePlatformB: "Большая Платформа B",
    oxygenator: "Кислородатор",
    mediumGenerator: "Средний Генератор",
    mediumWindTurbine: "Средняя Ветряная Турбина",
    tractor: "Трактор",

    largeTPlatform: "Большая Т-платформа",
    smallShuttle: "Малый Шаттл",
    landingPad: "Посадочная Площадка",
    drillMod1: "Модификация Бурового Оборудования 1",
    smallWindTurbine: "Малая Ветряная Турбина",
    tallPlatform: "Высокая Платформа",
    tallStorage: "Высокое Хранилище",
    drillStrength1: "Мощность Бурового Оборудования 1",
    exoRequestPlatform: "Платформа Экзоручных Запросов",
    largeWindTurbine: "Большая Ветряная Турбина",
    largePlatformC: "Большая Платформа C",
    largeCurvedPlatform: "Большая Изогнутая Платформа",
    largeStorage: "Большое Хранилище",
    xlWindTurbine: "Очень Большая Ветряная Турбина",
    extraLargePlatformA: "Очень Большая Платформа A",
    extraLargeCurvedPlatform: "Очень Большая Изогнутая Платформа",
    extraLargeStorage: "Очень Большое Хранилище",
    mediumShuttle: "Средний Шаттл",
    largeShuttle: "Большой Шаттл",
    worklight: "Рабочий Свет",
    smallSolarPanel: "Малая Солнечная Панель",
    extenders: "Удлинители",
    mediumSolarPanel: "Средняя Солнечная Панель",
    powerSensor: "Датчик Энергии",
    solarArray: "Солнечный Батарейный Блок",
    oxygenTank: "Баллон с Кислородом",

    mediumResourceCanister: "Средний Контейнер для Ресурсов",
    mediumFluidSoilCanister: "Средний Контейнер для Жидкости и Почвы",
    mediumGasCanister: "Средний Газовый Контейнер",
    largeResourceCaniester: "Большой Контейнер для Ресурсов",
    largeSolarPanel: "Большая Солнечная Панель",
    mediumShredder: "Средний Уничтожитель",
    largeShredder: "Большой Уничтожитель",
    extraLargePlatformB: "Дополнительно Большая Платформа B",
    extraLargePlatformC: "Дополнительно Большая Платформа C",
    figurinePlatform: "Фигурная Платформа",
    crane: "Кран",
    largeResourceCanister: "Большой Контейнер для Ресурсов",
    mediumStorageSilo: "Средний Хранилище Силоса",
    floodlight: "Флудлайт",
    powerCells: "Энергетические Ячейки",
    wideMod: "Широкий Мод",
    alignmentMod: "Модификация Выравнивания",
    inhibitorMod: "Модификация Ингибитора",
    boostMod: "Модификация Ускорения",
    narrowMod: "Узкий Мод",
    terrainAnalyzer: "Анализатор Местности",
    smallBattery: "Маленький Аккумулятор",
    batterySensor: "Датчик Аккумулятора",
    buttonRepeater: "Повторитель Кнопки",
    proximityRepeater: "Повторитель Приближения",
    delayRepeater: "Повторитель Задержки",
    countRepeater: "Повторитель Подсчета",
    recreationalSphere: "Развлекательная Сфера",
    largeRover: "Большой Ровер",
    paver: "Укладчик",
    drillMod3: "Модификация Бура 3",

    drillStrength3: "Сила бурения 3",
    fireworks: "Фейерверки",
    fieldShelter: "Полевой укрытие",
    portableOxygenator: "Портативный кислородатор",
    holographicFigurine: "Голографическая фигурка",
    mediumRover: "Средний ровер",
    shelter: "Укрытие",
    winch: "Лебёдка",
    autoExtractor: "Автоматический экстрактор",
    probeScanner: "Сканер зондов",
    hydrazineThruster: "Гидразиновый тягач",
    largeStorageSiloA: "Большой силос хранения A",
    largeStorageSiloB: "Большой силос хранения B",
    extraLargeShredder: "Огромный измельчитель",
    drillStrength2: "Сила бурения 2",
    hydrazineJetPack: "Гидразиновый реактивный ранец",
    drillMod2: "Модификация бурения 2",
    mediumTPlatform: "Средняя T-платформа",
    mediumBuggyHorn: "Средний сигнал тревоги для багги",
    smallCanister: "Маленький баллон",
    powerSwitch: "Электропереключатель",
    automoton001: "Автоматон 001",
    automoton002: "Автоматон 002",
    cubicObject: "Кубический объект",
    stellarObject: "Звездный объект",
    cosmigBauble: "Космический бублик",
    scrap: "Металлолом",
    event: "Событие",
    full: "Полный",

    levelingBlock: "Блок выравнивания",
    unlocked: "Разблокировано",
    smallCamera: "Маленькая камера",
    smallTrumpetHorn: "Маленький трубный рог",
    hoverboard: "Ховерборд",
    largeExtendedPlatform: "Большая расширенная платформа",
    largeActiveStorage: "Большое активное хранилище",
    largeFogHorn: "Большой туманный рог",
    vtol: "VTOL",
    sourceVtol: "Вертикальный взлет и посадка (VTOL)",
    printTitle: "Печать предметов",
    xlExtendedPlatform: "XL расширенная платформа",
    sourcePortableSmeltingFurnace: "Портативная плавильная печь",
    gravityGlobe: "Гравитационный глобус",
    easy: "Легкий",
    planetDetails: "Детали планеты",
    size: "Размер",
    medium: "Средний",
    difficulty: "Сложность",
    dayNigthCycle: "Цикл День/Ночь",
    minutes: "Минуты",
    sunPower: "Солнечная энергия",
    windPower: "Ветровая энергия",
    location: "Местоположение: ",
    caveLayer: "Пещерный слой",
    mantleLayer: "Мантийный слой",
    small: "Маленький",
    grayPlains: "Серые равнины",
    veryHigh: "Очень высокий",
    low: "Низкий",
    high: "Высокий",
    veryLow: "Очень низкий",
    purpleHills: "Фиолетовые холмы",
    mountains: "Горы",
    icePlains: "Ледяные равнины",
    hard: "Сложный",
    veryHard: "Очень сложный",    

    // Long Names
    backpackPrinter: "Рюкзачный принтер",
    smallPrinter: "Маленький принтер",
    mediumPrinter: "Средний принтер",
    largePrinter: "Большой принтер",
    soilCentrifuge: "Почвенная центрифуга",
    chemistryLab: "Химическая лаборатория",
    atmosphericCondenser: "Атмосферный конденсатор",
    tradePlatform: "Торговая платформа",
    smeltingFurnace: "Плавильная печь",
    
    // Printers table
    craftedAt: "Создано в",
    recipe: "Рецепт",
    unlockCost: "Стоимость разблокировки",
    powerConsumption: "Потребление энергии",
    "-": "-"
}