export default {
    //App commun texts
    welcome: 'ПРОСТОЙ ПУТЬ\nИСПОЛЬЗОВАТЬ\nАСТРОПЕДИЯ',
    userIdentification: 'Как зовут твоего\nастронера?',
    language: 'Язык: ',
    whatYouWant: 'Не видишь, что хочешь? ',
    contactUs: 'Свяжитесь с нами',
    contactUsDefaultName: 'Astroneer Player',
    contactUsMail: 'noreply',
    contactUsMessageFrom: '\n\n\nСообщение от: ',
    contactUsMessageReply: '\nОтветить на: ',
    contactUsWarnning: 'Вам нужно включить сообщение!',
    contactUsPlaceholderEmail: 'Эл. адрес',
    contactUsPlaceholderName: 'Имя',
    contactUsPlaceholderMessage: 'Сообщение',
    avatar: 'Аватар: ',
    name: 'Имя: ',
    aboutUs: 'О нас',
    aboutUsCredit: 'Кредиты',
    aboutUsDeveloped: 'Разработан MIDDLEWARE DEV',
    aboutUsDesign: 'Дизайн',
    aboutUsThanks: 'С особой благодарностью',
    warningTitle: 'Предупреждение',
    warningMessage: 'Изменения вступят в силу только после перезапуска Astropedia',
    warningButton: 'Ok',

    //Titles
    mainTitle: 'Астропедия',
    planetsTitle: 'Планеты',
    resourcesTitle: 'Ресурсы',
    favoritesTitle: 'Избранное',
    naturalResourcesTitle: 'природные ресурсы',
    atmosphericResourcesTitle: 'атмосферные ресурсы',
    sourceTitle: 'Источник',
    usesTitle: 'Использование',

    //Planet's names
    sylva: 'Сильва',
    desolo: 'Десоло',
    calidor: 'Калидор',
    vesania: 'Весания',
    novus: 'Новус',
    glacio: 'Гласио',
    atrox: 'Атрокс',

    //Resource's names
    ammonium: 'Аммоний',
    astronium: 'Астрониум',
    clay: 'Глина',
    compound: 'Compound',
    graphite: 'графит',
    hematite: 'Гематит',
    laterite: 'Латерит',
    lithium: 'Литий',
    malachite: 'Малахит',
    organic: 'Органиka',
    quartz: 'Кварц',
    resin: 'Смола',
    sphalerite: 'Сфалерит',
    titanite: 'Титанит',
    wolframite: 'Вольфрамит',
    aluminum: 'Алюминий',
    carbon: 'Углерод',
    ceramic: 'Керамиka',
    copper: 'Медь',
    glass: 'Стaклo',
    iron: 'Iron',
    titanium: 'Титан',
    tungsten: 'Вольфрам',
    zinc: 'Цинк',
    argon: 'Аргон',
    helium: 'гелий',
    hydrogen: 'Водород',
    methane: 'Метан',
    nitrogen: 'Азот',
    sulfur: 'Сера',
    aluminumAlloy: 'Алюминиевый',
    diamond: 'Алмаз',
    explosivePowder: 'пороx',
    hydrazine: 'гидразин',
    graphene: 'графен',
    nanocarbonAlloy: 'Наноу... сплав',
    plastic: 'Пластик',
    rubber: 'Резина',
    silicone: 'Силикон',
    steel: 'Сталb',
    titaniumAlloy: 'сплав титана',
    tungstenCarbide: 'вольфрам к...',

    //Sources and Items name
    sourceAllPlanets: 'Все планеты',
    soilCentrifuge: 'центрифуга почвы',
    tradePlatform: 'Платформа обменa',
    smallPrinter: 'малый принтер',
    solidFuelThruster: 'двигатель ha твердom топливe',
    chemistryLab: 'Химическая лаборатория',
    exoChip: 'EXO-Чип',
    packager: 'Упаковщик',
    solidFuelJumpJet: 'реакт. ha твердom топливо',
    dynamite: 'Динамит',
    smeltingFurnace: 'Плавильная печь',
    backpackPrinter: 'Рюкзак Принтер',
    smallGenerator: 'Малый генератор',
    tether: 'Привязь',
    roverSeat: 'Ровер Сиденье',
    mediumPrinter: 'Средний принтер',
    trailer: 'Трейлер',
    researchChamber: 'Исследовательская палата',
    largePrinter: 'Большой принтер',
    largeRoverSeat: 'Большое сиденье вездехода',
    buggy: 'Багги',
    splitter: 'Сплиттер',
    autoArm: 'Auto Arm',
    mediumBattery: 'Средняя батарея',
    rtg: 'RTG',
    glowsticks: 'Светящиеся палочки',
    beacon: 'Маяк',
    storageSensor: 'Датчик хранения',
    mediumSensorArch: 'Средняя сенсорная дуга',
    largeSensorRing: 'Большое сенсорное кольцо',
    largeSensorHoopA: 'Большой сенсорный обруч A',
    largeSensorHoopB: 'Большой сенсорный обруч B',
    xlSensorArch: 'XL Сенсорная дуга',
    xlSensorCanopy: 'Навес датчика XL',
    xlSensorHoopA: 'XL Сенсорное кольцо A',
    xlSensorHoopB: 'XL Сенсорное кольцо B',
    canister: 'Канистра',
    oxygenFilter: 'Кислородный фильтр',
    mediumStorage: 'Среднее хранилище',
    mediumPlatformA: 'Средняя платформа А',
    mediumPlatformB: 'Средняя платформа B',
    mediumPlatformC: 'Средняя платформа C',
    largePlatformA: 'Большая платформа А',
    largePlatformB: 'Большая платформа B',
    oxygenator: 'Оксигенатор',
    mediumGenerator: 'Средний генератор',
    mediumWindTurbine: 'Средняя ветряная турбина',
    tractor: 'Трактор',
    largeTPlatform: 'Большая Т-платформа',
    smallShuttle: 'Маленький шаттл',
    landingPad: 'Посадочная площадка',
    sourceAluminumAlloy: 'Алюминиевый сплав',
    sourceExplosivePowder: 'Взрывчатый порошок',
    sourceNanocarbonAlloy: 'Наноуглеродный сплав',
    sourceTungstenCarbide: 'вольфрам карбид',
    drillMod1: 'Дрель мод 1',
    smallWindTurbine: 'Малая ветряная турбина',
    tallPlatform: 'Высокая платформа',
    tallStorage: 'Высокая платформа',
    drillStrength1: 'Прочность сверла 1',
    exoRequestPlatform: 'Платформа экзо-запросов',
    largeWindTurbine: 'Большая ветряная турбина',
    largePlatformC: 'Большая платформа С',
    largeCurvedPlatform: 'Большая изогнутая платформа',
    largeStorage: 'Большое хранилище',
    xlWindTurbine: 'Xl ветряная турбина',
    extraLargePlatformA: 'Очень большая платформа А',
    extraLargeCurvedPlatform: 'Очень большая изогнутая платформа',
    extraLargeStorage: 'Очень большое хранилище',
    mediumShuttle: 'Средний шаттл',
    largeShuttle: 'Большой шаттл',
    worklight: 'Рабочий свет',
    smallSolarPanel: 'Малая солнечная панель',
    extenders: 'Удлинители',
    mediumSolarPanel: 'Средняя солнечная панель',
    powerSensor: 'Датчик мощности',
    solarArray: 'Солнечная батарея',
    oxygenTank: 'Кислородный баллон',
    mediumResourceCanister: 'Средняя канистра ресурсов',
    mediumFluidSoilCanister: 'Средняя канистра с жидкостью и почвой',
    mediumGasCanister: 'Канистра среднего газа',
    atmosphericCondenser: 'Атмосферный конденсатор',
    largeResourceCaniester: 'Большая канистра ресурсов',
    largeSolarPanel: 'Большая солнечная панель',
    mediumShredder: 'Средний измельчитель',
    largeShredder: 'Большой измельчитель',
    extraLargePlatformB: 'Очень большая платформа B',
    extraLargePlatformC: 'Очень большая платформа C',
    figurinePlatform: 'Фигурка Платформа',
    crane: 'кран',
    largeResourceCanister: 'Большая канистра ресурсов',
    mediumStorageSilo: 'Бункер для среднего хранения',
    floodlight: 'Прожектор',
    powerCells: 'Силовые элементы',
    wideMod: 'Широкий мод',
    alignmentMod: 'Мод выравнивания',
    inhibitorMod: 'Ингибитор Мод',
    boostMod: 'Ускоряющий мод',
    narrowMod: 'Узкий мод',
    terrainAnalyzer: 'Анализатор местности',
    smallBattery: 'Маленькая батарея',
    batterySensor: 'Датчик батареи',
    buttonRepeater: 'Кнопка повторителя',
    proximityRepeater: 'Бесконтактный повторитель',
    delayRepeater: 'Повторитель задержки',
    countRepeater: 'Повторитель счета',
    recreationalSphere: 'Рекреационная сфера',
    largeRover: 'Большой Ровер',
    paver: 'асфальтоукладчик',
    drillMod3: 'Дрель Мод 3',
    drillStrength3: 'Прочность сверла 3',
    fireworks: 'фейерверк',
    fieldShelter: 'Полевой приют',
    portableOxygenator: 'Портативный оксигенатор',
    holographicFigurine: 'Голографическая фигурка',
    mediumRover: 'Средний вездеход',
    shelter: 'Приют',
    winch: 'лебедка',
    autoExtractor: 'Автоматический экстрактор',
    probeScanner: 'Сканер зонда',
    hydrazineThruster: 'Гидразиновый двигатель',
    largeStorageSiloA: 'Большой бункер для хранения A',
    largeStorageSiloB: 'Большой бункер для хранения B',
    extraLargeShredder: 'Очень большой измельчитель',
    drillStrength2: 'Прочность сверла 2',
    hydrazineJetPack: 'Гидразиновый реактивный ранец',
    drillMod2: 'Дрель Мод 2'
}