export default {
    //App commun texts
    welcome: 'ПРОСТОЙ ПУТЬ\nИСПОЛЬЗОВАТЬ\nАСТРОПЕДИЯ',
    userIdentification: 'Как зовут твоего\nастронера?',

    //Titles
    mainTitle: 'Астропедия',
    planetsTitle: 'Планеты',
    resourcesTitle: 'Ресурсы',
    favoritesTitle: 'Избранное',
    naturalResourcesTitle: 'природные ресурсы',
    atmosphericResourcesTitle: 'атмосферные ресурсы',
    sourceTitle: 'Источник',
    usesTitle: 'Использование',

    //Planet's names
    sylva: 'Сильва',
    desolo: 'Десоло',
    calidor: 'Калидор',
    vesania: 'Весания',
    novus: 'Новус',
    glacio: 'Гласио',
    atrox: 'Атрокс',

    //Resource's names
    ammonium: 'Аммоний',
    astronium: 'Астрониум',
    clay: 'Глина',
    compound: 'Compound',
    graphite: 'графит',
    hematite: 'Гематит',
    laterite: 'Латерит',
    lithium: 'Литий',
    malachite: 'Малахит',
    organic: 'Органиka',
    quartz: 'Кварц',
    resin: 'Смола',
    sphalerite: 'Сфалерит',
    titanite: 'Титанит',
    wolframite: 'Вольфрамит',
    aluminum: 'Алюминий',
    carbon: 'Углерод',
    ceramic: 'Керамиka',
    copper: 'Медь',
    glass: 'Стaклo',
    iron: 'Iron',
    titanium: 'Титан',
    tungsten: 'Вольфрам',
    zinc: 'Цинк',
    argon: 'Аргон',
    helium: 'гелий',
    hydrogen: 'Водород',
    methane: 'Метан',
    nitrogen: 'Азот',
    sulfur: 'Сера',
    aluminumAlloy: 'Алюминиевый',
    diamond: 'Алмаз',
    explosivePowder: 'пороx',
    hydrazine: 'гидразин',
    graphene: 'графен',
    nanocarbonAlloy: 'Наноуглеродный сплав',
    plastic: 'Пластик',
    rubber: 'Резина',
    silicone: 'Силикон',
    steel: 'Сталb',
    titaniumAlloy: 'титановый сплав',
    tungstenCarbide: 'Карбид вольфрама',

    //Sources and Items name
    sourceAllPlanets: 'Все планеты',
    soilCentrifuge: 'центрифуга почвы',
    tradePlatform: 'Платформа обменa',
    smallPrinter: 'малый принтер',
    solidFuelThruster: 'двигатель ha твердom топливe',
    chemistryLab: 'Химическая лаборатория',
    exoChip: 'EXO-Чип',
    packager: 'Упаковщик',
    solidFuelJumpJet: 'реакт. ha твердom топливо',
    dynamite: 'Динамит',
    smeltingFurnace: 'Плавильная печь',
    backpackPrinter: 'Backpack Printer',
    smallGenerator: 'Small Generator',
    tether: 'Tether',
    roverSeat: 'Rover Seat',
    mediumPrinter: 'Medium Printer',
    trailer: 'Trailer',
    researchChamber: 'Research Chamber',
    largePrinter: 'Large Printer',
    largeRoverSeat: 'Large Rover Seat',
    buggy: 'Buggy',
    splitter: 'Splitter',
    autoArm: 'Auto Arm',
    mediumBattery: 'Medium Battery',
    rtg: 'RTG',
    glowsticks: 'Glowsticks',
    beacon: 'Beacon',
    storageSensor: 'Storage Sensor',
    mediumSensorArch: 'Medium Sensor Arch',
    largeSensorRing: 'Large Sensor Ring',
    largeSensorHoopA: 'Large Sensor Hoop A',
    largeSensorHoopB: 'Large Sensor Hoop B',
    xlSensorArch: 'Xl Sensor Arch',
    xlSensorCanopy: 'Xl Sensor Canopy',
    xlSensorHoopA: 'Xl Sensor Hoop A',
    xlSensorHoopB: 'Xl Sensor Hoop B',
    canister: 'Canister',
    oxygenFilter: 'Oxygen Filter',
    mediumStorage: 'Medium Storage',
    mediumPlatformA: 'Medium Platform A',
    mediumPlatformB: 'Medium Platform B',
    mediumPlatformC: 'Medium Platform C',
    largePlatformA: 'Large Platform A',
    largePlatformB: 'Large Platform B',
    oxygenator: 'Oxygenator',
    mediumGenerator: 'Medium Generator',
    mediumWindTurbine: 'Medium Wind Turbine',
    tractor: 'Tractor',
    largeTPlatform: 'Large T-Platform',
    smallShuttle: 'Small Shuttle',
    landingPad: 'Landing Pad',
    sourceAluminumAlloy: 'Aluminum Alloy',
    sourceExplosivePowder: 'Explosive Powder',
    sourceNanocarbonAlloy: 'Nanocarbon Alloy',
    sourceTungstenCarbide: 'Tungsten Carbide',
    drillMod1: 'Drill Mod 1',
    smallWindTurbine: 'Small Wind Turbine',
    tallPlatform: 'Tall Platform',
    tallStorage: 'Tall Storage',
    drillStrength1: 'Drill Strength 1',
    exoRequestPlatform: 'Exo Request Platform',
    largeWindTurbine: 'Large Wind Turbine',
    largePlatformC: 'Large Platform C',
    largeCurvedPlatform: 'Large Curved Platform',
    largeStorage: 'Large Storage',
    xlWindTurbine: 'Xl Wind Turbine',
    extraLargePlatformA: 'Extra Large Platform A',
    extraLargeCurvedPlatform: 'Extra Large Curved Platform',
    extraLargeStorage: 'Extra Large Storage',
    mediumShuttle: 'Medium Shuttle',
    largeShuttle: 'Large Shuttle',
    worklight: 'Worklight',
    smallSolarPanel: 'Small Solar Panel',
    extenders: 'Extenders',
    mediumSolarPanel: 'Medium Solar Panel',
    powerSensor: 'Power Sensor',
    solarArray: 'Solar Array',
    oxygenTank: 'Oxygen Tank',
    mediumResourceCanister: 'Medium Resource Canister',
    mediumFluidSoilCanister: 'Medium Fluid & Soil Canister',
    mediumGasCanister: 'Medium Gas Canister',
    atmosphericCondenser: 'Atmospheric Condenser',
    largeResourceCaniester: 'Large Resource Caniester',
    largeSolarPanel: 'Large Solar Panel',
    mediumShredder: 'Medium Shredder',
    largeShredder: 'Large Shredder',
    extraLargePlatformB: 'Extra Large Platform B',
    extraLargePlatformC: 'Extra Large Platform C',
    figurinePlatform: 'Figurine Platform',
    crane: 'Crane',
    largeResourceCanister: 'Large Resource Canister',
    mediumStorageSilo: 'Medium Storage Silo',
    floodlight: 'Floodlight',
    powerCells: 'Power Cells',
    wideMod: 'Wide Mod',
    alignmentMod: 'Alignment Mod',
    inhibitorMod: 'Inhibitor Mod',
    boostMod: 'Boost Mod',
    narrowMod: 'Narrow Mod',
    terrainAnalyzer: 'Terrain Analyzer',
    smallBattery: 'Small Battery',
    batterySensor: 'Battery Sensor',
    buttonRepeater: 'Button Repeater',
    proximityRepeater: 'Proximity Repeater',
    delayRepeater: 'Delay Repeater',
    countRepeater: 'Count Repeater',
    recreationalSphere: 'Recreational Sphere',
    largeRover: 'Large Rover',
    paver: 'paver',
    drillMod3: 'Drill Mod 3',
    drillStrength3: 'Drill Strength 3',
    fireworks: 'fireworks',
    fieldShelter: 'Field Shelter',
    portableOxygenator: 'Portable Oxygenator',
    holographicFigurine: 'Holographic Figurine',
    mediumRover: 'Medium Rover',
    shelter: 'Shelter',
    winch: 'winch',
    autoExtractor: 'Auto Extractor',
    probeScanner: 'Probe Scanner',
    hydrazineThruster: 'Hydrazine Thruster',
    largeStorageSiloA: 'Large Storage Silo A',
    largeStorageSiloB: 'Large Storage Silo B',
    extraLargeShredder: 'Extra Large Shredder',
    drillStrength2: 'Drill Strength 2',
    hydrazineJetPack: 'Hydrazine Jet Pack',
    drillMod2: 'Drill Mod 2'
}