export default {
    //App commun texts
    welcome: 'УДОБНЫЙ СПОСОБ\nИСПОЛЬЗОВАТЬ\nASTROPEDIA',
    userIdentification: 'Как вас зовут в Astroneer?',
    language: 'Язык: ',
    whatYouWant: 'Не нашли то, что искали? ',
    contactUs: 'Свяжитесь с нами',
    contactUsDefaultName: 'Игрок Astroneer',
    contactUsMail: 'безответный',
    contactUsMessageFrom: '\n\n\nСообщение от: ',
    contactUsMessageReply: '\nОтветить на: ',
    contactUsWarnning: 'Вы должны включить сообщение!',
    contactUsPlaceholderEmail: 'Email',
    contactUsPlaceholderName: 'Имя',
    contactUsPlaceholderMessage: 'Сообщение',
    avatar: 'Аватар: ',
    name: 'Имя: ',
    aboutUs: 'О нас',
    aboutUsCredit: 'Кредиты',
    aboutUsDeveloped: 'Разработано MIDDLEWARE DEV',
    aboutUsDesign: 'Дизайн',
    aboutUsThanks: 'Особая благодарность',
    aboutUsTranslation: 'Переводы',
    warningTitle: 'Предупреждение',
    warningMessage: 'Изменения вступят в силу после перезапуска Astropedia',
    warningButton: 'Ок',

    //Titles
    mainTitle: 'Astropedia',
    planetsTitle: 'Планеты',
    resourcesTitle: 'Ресурсы',
    favoritesTitle: 'Избранное',
    naturalResourcesTitle: 'Природные ресурсы',
    atmosphericResourcesTitle: 'Атмосферные ресурсы',
    sourceTitle: 'Источник',
    usesTitle: 'Применение',
    printers: 'Принтеры',

    //Planet's names
    sylva: 'Сильва',
    desolo: 'Десоло',
    calidor: 'Калидор',
    vesania: 'Весания',
    novus: 'Новус',
    glacio: 'Гласио',
    atrox: 'Атрокс',    

    //Resource's names
    ammonium: 'Аммоний',
    astronium: 'Астроний',
    clay: 'Глина',
    compound: 'Соединение',
    graphite: 'Графит',
    hematite: 'Гематит',
    laterite: 'Латерит',
    lithium: 'Литий',
    malachite: 'Малахит',
    organic: 'Органика',
    quartz: 'Кварц',
    resin: 'Смола',
    sphalerite: 'Сфалерит',
    titanite: 'Титанит',
    wolframite: 'Вольфрамит',
    aluminum: 'Алюминий',
    carbon: 'Углерод',
    ceramic: 'Керамика',
    copper: 'Медь',
    glass: 'Стекло',
    iron: 'Железо',
    titanium: 'Титан',
    tungsten: 'Вольфрам',
    zinc: 'Цинк',
    argon: 'Аргон',
    helium: 'Гелий',
    hydrogen: 'Водород',
    methane: 'Метан',
    nitrogen: 'Азот',
    sulfur: 'Сера',
    aluminumAlloy: 'Сплав Ал',
    diamond: 'Алмаз',
    explosivePowder: 'Взрывч. вещ.',
    hydrazine: 'Гидразин',
    graphene: 'Графен',
    nanocarbonAlloy: 'Наноуглерод',
    plastic: 'Пластик',
    rubber: 'Резина',
    silicone: 'Силикон',
    steel: 'Сталь',
    titaniumAlloy: 'Сплав титана',
    tungstenCarbide: 'Карбид Вольф.',    

    //Sources and Items name
    sourceAllPlanets: 'Все Планеты',
    solidFuelThruster: 'Твердотопливный Тягач',
    exoChip: 'Экзо-Чип',
    packager: 'Пакетировщик',
    solidFuelJumpJet: 'Твердотопливные Джамперы',
    dynamite: 'Динамит',
    smallGenerator: 'Маленький Генератор',
    tether: 'Трос',
    roverSeat: 'Сиденье для Ровера',
    trailer: 'Прицеп',
    researchChamber: 'Исследовательская Камера',
    largeRoverSeat: 'Большое Сиденье для Ровера',
    buggy: 'Багги',
    splitter: 'Сплиттер',
    autoArm: 'Авто Рука',
    mediumBattery: 'Средний Аккумулятор',
    rtg: 'РТГ',
    glowsticks: 'Светящиеся Палочки',
    beacon: 'Маяк',
    storageSensor: 'Сенсор Хранилища',
    mediumSensorArch: 'Медиум Датчик Арки',
    largeSensorRing: 'Большое Кольцо Датчика',
    largeSensorHoopA: 'Большое Кольцо Датчика A',
    largeSensorHoopB: 'Большое Кольцо Датчика B',
    xlSensorArch: 'XL Датчик Арки',
    xlSensorCanopy: 'XL Датчик Конуса',
    xlSensorHoopA: 'XL Датчик Кольцо A',
    xlSensorHoopB: 'XL Датчик Кольцо B',
    canister: 'Баллон',
    oxygenFilter: 'Фильтр для Кислорода',
    mediumStorage: 'Среднее Хранилище',
    mediumPlatformA: 'Средняя Платформа A',
    mediumPlatformB: 'Средняя Платформа B',
    mediumPlatformC: 'Средняя Платформа C',
    largePlatformA: 'Большая Платформа A',
    largePlatformB: 'Большая Платформа B',
    oxygenator: 'Оксигенатор',
    mediumGenerator: 'Средний Генератор',
    mediumWindTurbine: 'Средний Ветряк',
    tractor: 'Трактор',
    largeTPlatform: 'Большая T-Платформа',
    smallShuttle: 'Маленький Шаттл',
    landingPad: 'Посадочная Площадка',
    sourceAluminumAlloy: 'Сплав Алюминия',
    sourceExplosivePowder: 'Взрывчатое Вещество',
    sourceNanocarbonAlloy: 'Сплав Наноуглерода',
    sourceTungstenCarbide: 'Карбид Вольфрама',
    drillMod1: 'Модификация Сверла 1',
    smallWindTurbine: 'Маленький Ветряк',
    tallPlatform: 'Высокая Платформа',
    tallStorage: 'Высокое Хранилище',
    drillStrength1: 'Сила Сверла 1',
    exoRequestPlatform: 'Платформа Запросов Экзо',
    largeWindTurbine: 'Большой Ветряк',
    largePlatformC: 'Большая Платформа C',
    largeCurvedPlatform: 'Большая Изогнутая Платформа',
    largeStorage: 'Большое Хранилище',
    xlWindTurbine: 'XL Ветряк',
    extraLargePlatformA: 'Особо Большая Платформа A',
    extraLargeCurvedPlatform: 'Особо Большая Изогнутая Платформа',
    extraLargeStorage: 'Особо Большое Хранилище',
    mediumShuttle: 'Средний Шаттл',
    largeShuttle: 'Большой Шаттл',
    worklight: 'Рабочий Свет',
    smallSolarPanel: 'Маленькая Солнечная Панель',
    extenders: 'Удлинители',
    mediumSolarPanel: 'Средняя Солнечная Панель',
    powerSensor: 'Датчик Энергии',
    solarArray: 'Солнечный Архив',
    oxygenTank: 'Баллон с Кислородом',
    mediumResourceCanister: 'Средний Баллон Ресурсов',
    mediumFluidSoilCanister: 'Средний Баллон Жидкости и Почвы',
    mediumGasCanister: 'Средний Газовый Баллон',
    largeResourceCanister: 'Большой Баллон Ресурсов',
    largeSolarPanel: 'Большая Солнечная Панель',
    mediumShredder: 'Средний Шредер',
    largeShredder: 'Большой Шредер',
    extraLargePlatformB: 'Особо Большая Платформа B',
    extraLargePlatformC: 'Особо Большая Платформа C',
    figurinePlatform: 'Платформа для Фигурок',
    crane: 'Кран',
    largeResourceCanister: 'Большой Баллон Ресурсов',
    mediumStorageSilo: 'Средний Силос для Хранилища',
    floodlight: 'Прожектор',
    powerCells: 'Энергетические Ячейки',
    wideMod: 'Широкий Мод',
    alignmentMod: 'Модификация Выравнивания',
    inhibitorMod: 'Модификация Защиты',
    boostMod: 'Ускоряющая Модификация',
    narrowMod: 'Модификация Узкости',
    terrainAnalyzer: 'Анализатор Местности',
    smallBattery: 'Маленький Аккумулятор',
    batterySensor: 'Датчик Батареи',
    buttonRepeater: 'Репитер Кнопок',
    proximityRepeater: 'Репитер Близости',
    delayRepeater: 'Репитер Задержки',
    countRepeater: 'Репитер Счета',
    recreationalSphere: 'Развлекательная Сфера',
    largeRover: 'Большой Ровер',
    paver: 'Павер',
    drillMod3: 'Модификация Сверла 3',
    drillStrength3: 'Сила Сверла 3',
    fireworks: 'Фейерверк',
    fieldShelter: 'Полевой Укрытие',
    portableOxygenator: 'Портативный Оксигенатор',
    holographicFigurine: 'Голографическая Фигурка',
    mediumRover: 'Средний Ровер',
    shelter: 'Убежище',
    winch: 'Лебедка',
    autoExtractor: 'Авто Экстрактор',
    probeScanner: 'Сканер Сонды',
    hydrazineThruster: 'Гидразиновый Двигатель',
    largeStorageSiloA: 'Большой Хранилище Silo A',
    largeStorageSiloB: 'Большой Хранилище Silo B',
    extraLargeShredder: 'Очень Большой Шредер',
    drillStrength2: 'Сила Сверла 2',
    hydrazineJetPack: 'Реактивный Ранец на Гидразине',
    drillMod2: 'Модификация Сверла 2',
    mediumTPlatform: 'Средняя T-Платформа',
    mediumBuggyHorn: 'Средний Гудок для Багги',
    smallCanister: 'Маленький Баллон',
    powerSwitch: 'Выключатель',
    automoton001: 'Автомотон 001',
    automoton002: 'Автомотон 002',
    cubicObject: 'Кубический Объект',
    stellarObject: 'Звездный Объект',
    cosmigBauble: 'Космический Шарик',
    scrap: 'Мусор',
    event: 'Событие',
    full: 'Полный',
    levelingBlock: 'Блок Выравнивания',
    unlocked: 'Разблокировано',
    smallCamera: 'Маленькая Камера',
    smallTrumpetHorn: 'Маленькая Трубчатая Гудок',
    hoverboard: 'Летающая Доска',
    largeExtendedPlatform: 'Большая Расширенная Платформа',
    largeActiveStorage: 'Большое Активное Хранилище',
    largeFogHorn: 'Большой Гудок для Тумана',
    vtol: 'VTOL',
    sourceVtol: 'Вертикальный Взлет и Посадка (VTOL)',
    printTitle: 'Печать Предметов',
    xlExtendedPlatform: 'Очень Большая Расширенная Платформа',
    sourcePortableSmeltingFurnace: 'Переносная Плавильня',
    gravityGlobe: 'Гравитационный Шар',
    easy: 'Легко',
    planetDetails: 'Детали Планеты',
    size: 'Размер',
    medium: 'Средний',
    difficulty: 'Сложность',
    dayNigthCycle: 'День/Ночь',
    minutes: 'Минуты',
    sunPower: 'Солнечная Энергия',
    windPower: 'Ветряная Энергия',
    location: 'Местонахождение: ',
    caveLayer: 'Слой Пещеры',
    mantleLayer: 'Слой Мантии',
    small: 'Маленький',
    grayPlains: 'Серые Равнины',
    veryHigh: 'Очень Высоко',
    low: 'Низко',
    high: 'Высоко',
    veryLow: 'Очень Низко',
    purpleHills: 'Пурпурные Холмы',
    mountains: 'Горы',
    icePlains: 'Ледяные Равнины',
    hard: 'Сложно',
    veryHard: 'Очень Сложно',    

    // Long Names
    backpackPrinter: 'Рюкзак',
    smallPrinter: 'Маленькая Друкарка',
    mediumPrinter: 'Средняя Друкарка',
    largePrinter: 'Большая Друкарка',
    soilCentrifuge: 'Повітряна Сепаратор',
    chemistryLab: 'Хімічна Лабораторія',
    atmosphericCondenser: 'Конденсатор Атмосфери',
    tradePlatform: 'Торгова Платформа',
    smeltingFurnace: 'Піч для Плавлення',
    
    backpack: 'Рюкзак',
    sourceSmallPrinter: 'Маленькая Др.',
    sourceMediumPrinter: 'Средняя Друк.',
    sourceLargePrinter: 'Бол. Друкарка',
    sourceChemistryLab: 'Хімічна Лаб',
    sourceSoilCentrifuge: 'Повітря Сеп.',
    sourceAtmosphericCondenser: 'Атмосф. Конд',
    sourceTradePlatform: 'Торг. Платф.',
    sourceSmeltingFurnace: 'Піч Плавлення',    
}