import React from 'react';

export const images = {
    welcome: require('../img/iconSylva.png'),
    f: require('../img/f.png'),
    logo: require('../img/logo.png'),
    confirm: require('../img/confirm.png'),
    player: require('../img/player.png'),
    sylva: require('../img/sylva.png'),
    desolo: require('../img/desolo.png'),
    calidor: require('../img/calidor.png'),
    vesania: require('../img/vesania.png'),
    novus: require('../img/novus.png'),
    glacio: require('../img/glacio.png'),
    atrox: require('../img/atrox.png'),
    compound: require('../img/compound.png'),
    favIcon: require('../img/favIcon.png'),
    iconSylva: require('../img/iconSylva.png'),
    nuggetSphalerite: require('../img/nuggetSphalerite.png'),
    sphalerite: require('../img/sphalerite.png'),
    nuggetMalachite: require('../img/nuggetMalachite.png'),
    malachite: require('../img/malachite.png'),
    nuggetHydrogen: require('../img/nuggetHydrogen.png'),
    hydrogen: require('../img/hydrogen.png'),
    nuggetNitrogen: require('../img/nuggetNitrogen.png'),
    nitrogen: require('../img/nitrogen.png'),
    iconDesolo: require('../img/iconDesolo.png'),
    wolframite: require('../img/wolframite.png'),
    nuggetWolframite: require('../img/nuggetWolframite.png'),
    iconCalidor: require('../img/iconCalidor.png'),
    sulfur: require('../img/sulfur.png'),
    nuggetSulfur: require('../img/nuggetSulfur.png'),
    iconVesania: require('../img/iconVesania.png'),
    argon: require('../img/argon.png'),
    nuggetArgon: require('../img/nuggetArgon.png'),
    titanite: require('../img/titanite.png'),
    nuggetTitanite: require('../img/nuggetTitanite.png'),
    lithium: require('../img/lithium.png'),
    nuggetLithium: require('../img/nuggetLithium.png')
}